/*******************************************************************************
* Filename      : syscfgcompopampregisters.hpp
*
* Details       : System configuration controller _Comparator and Operational
*                 amplifier. This header file is auto-generated for STM32F303
*                 device.
*
*
*******************************************************************************/

#if !defined(SYSCFGCOMPOPAMPREGISTERS_HPP)
#define SYSCFGCOMPOPAMPREGISTERS_HPP

#include "syscfgcompopampfieldvalues.hpp"  //for Bits Fields defs 
#include "registerbase.hpp"   //for RegisterBase
#include "register.hpp"       //for Register
#include "accessmode.hpp"     //for ReadMode, WriteMode, ReadWriteMode  

struct SYSCFG_COMP_OPAMP
{
  struct SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base {} ;

  struct SYSCFG_CFGR1 : public RegisterBase<0x40010000, 32, ReadWriteMode>
  {
    using MEM_MODE = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_MEM_MODE_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 0, 2, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using USB_IT_RMP = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_USB_IT_RMP_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 5, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using TIM1_ITR_RMP = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_TIM1_ITR_RMP_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 6, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using DAC_TRIG_RMP = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_DAC_TRIG_RMP_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using ADC24_DMA_RMP = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_ADC24_DMA_RMP_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 8, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using TIM16_DMA_RMP = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_TIM16_DMA_RMP_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 11, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using TIM17_DMA_RMP = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_TIM17_DMA_RMP_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 12, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using TIM6_DAC1_DMA_RMP = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_TIM6_DAC1_DMA_RMP_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 13, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using TIM7_DAC2_DMA_RMP = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_TIM7_DAC2_DMA_RMP_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 14, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using I2C_PB6_FM = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_I2C_PB6_FM_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 16, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using I2C_PB7_FM = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_I2C_PB7_FM_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 17, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using I2C_PB8_FM = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_I2C_PB8_FM_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 18, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using I2C_PB9_FM = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_I2C_PB9_FM_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 19, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using I2C1_FM = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_I2C1_FM_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 20, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using I2C2_FM = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_I2C2_FM_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 21, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using ENCODER_MODE = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_ENCODER_MODE_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 22, 2, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using FPU_IT = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_FPU_IT_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 26, 6, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base> ;
    using FieldValues = SYSCFG_COMP_OPAMP_SYSCFG_CFGR1_FPU_IT_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_CFGR1Pack  = Register<0x40010000, 32, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR1Base, T...> ;

  struct SYSCFG_COMP_OPAMPSYSCFG_EXTICR1Base {} ;

  struct SYSCFG_EXTICR1 : public RegisterBase<0x40010008, 32, ReadWriteMode>
  {
    using EXTI3 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR1_EXTI3_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR1, 12, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR1Base> ;
    using EXTI2 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR1_EXTI2_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR1, 8, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR1Base> ;
    using EXTI1 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR1_EXTI1_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR1, 4, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR1Base> ;
    using EXTI0 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR1_EXTI0_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR1, 0, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR1Base> ;
    using FieldValues = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR1_EXTI0_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_EXTICR1Pack  = Register<0x40010008, 32, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR1Base, T...> ;

  struct SYSCFG_COMP_OPAMPSYSCFG_EXTICR2Base {} ;

  struct SYSCFG_EXTICR2 : public RegisterBase<0x4001000C, 32, ReadWriteMode>
  {
    using EXTI7 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR2_EXTI7_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR2, 12, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR2Base> ;
    using EXTI6 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR2_EXTI6_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR2, 8, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR2Base> ;
    using EXTI5 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR2_EXTI5_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR2, 4, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR2Base> ;
    using EXTI4 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR2_EXTI4_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR2, 0, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR2Base> ;
    using FieldValues = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR2_EXTI4_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_EXTICR2Pack  = Register<0x4001000C, 32, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR2Base, T...> ;

  struct SYSCFG_COMP_OPAMPSYSCFG_EXTICR3Base {} ;

  struct SYSCFG_EXTICR3 : public RegisterBase<0x40010010, 32, ReadWriteMode>
  {
    using EXTI11 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR3_EXTI11_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR3, 12, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR3Base> ;
    using EXTI10 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR3_EXTI10_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR3, 8, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR3Base> ;
    using EXTI9 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR3_EXTI9_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR3, 4, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR3Base> ;
    using EXTI8 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR3_EXTI8_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR3, 0, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR3Base> ;
    using FieldValues = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR3_EXTI8_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_EXTICR3Pack  = Register<0x40010010, 32, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR3Base, T...> ;

  struct SYSCFG_COMP_OPAMPSYSCFG_EXTICR4Base {} ;

  struct SYSCFG_EXTICR4 : public RegisterBase<0x40010014, 32, ReadWriteMode>
  {
    using EXTI15 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR4_EXTI15_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR4, 12, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR4Base> ;
    using EXTI14 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR4_EXTI14_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR4, 8, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR4Base> ;
    using EXTI13 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR4_EXTI13_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR4, 4, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR4Base> ;
    using EXTI12 = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR4_EXTI12_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR4, 0, 4, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR4Base> ;
    using FieldValues = SYSCFG_COMP_OPAMP_SYSCFG_EXTICR4_EXTI12_Values<SYSCFG_COMP_OPAMP::SYSCFG_EXTICR4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_EXTICR4Pack  = Register<0x40010014, 32, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_EXTICR4Base, T...> ;

  struct SYSCFG_COMP_OPAMPSYSCFG_CFGR2Base {} ;

  struct SYSCFG_CFGR2 : public RegisterBase<0x40010018, 32, ReadWriteMode>
  {
    using LOCUP_LOCK = SYSCFG_COMP_OPAMP_SYSCFG_CFGR2_LOCUP_LOCK_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR2, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR2Base> ;
    using SRAM_PARITY_LOCK = SYSCFG_COMP_OPAMP_SYSCFG_CFGR2_SRAM_PARITY_LOCK_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR2, 1, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR2Base> ;
    using PVD_LOCK = SYSCFG_COMP_OPAMP_SYSCFG_CFGR2_PVD_LOCK_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR2, 2, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR2Base> ;
    using BYP_ADD_PAR = SYSCFG_COMP_OPAMP_SYSCFG_CFGR2_BYP_ADD_PAR_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR2, 4, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR2Base> ;
    using SRAM_PEF = SYSCFG_COMP_OPAMP_SYSCFG_CFGR2_SRAM_PEF_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR2, 8, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR2Base> ;
    using FieldValues = SYSCFG_COMP_OPAMP_SYSCFG_CFGR2_SRAM_PEF_Values<SYSCFG_COMP_OPAMP::SYSCFG_CFGR2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_CFGR2Pack  = Register<0x40010018, 32, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_CFGR2Base, T...> ;

  struct SYSCFG_COMP_OPAMPSYSCFG_RCRBase {} ;

  struct SYSCFG_RCR : public RegisterBase<0x40010004, 32, ReadWriteMode>
  {
    using PAGE0_WP = SYSCFG_COMP_OPAMP_SYSCFG_RCR_PAGE0_WP_Values<SYSCFG_COMP_OPAMP::SYSCFG_RCR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_RCRBase> ;
    using PAGE1_WP = SYSCFG_COMP_OPAMP_SYSCFG_RCR_PAGE1_WP_Values<SYSCFG_COMP_OPAMP::SYSCFG_RCR, 1, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_RCRBase> ;
    using PAGE2_WP = SYSCFG_COMP_OPAMP_SYSCFG_RCR_PAGE2_WP_Values<SYSCFG_COMP_OPAMP::SYSCFG_RCR, 2, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_RCRBase> ;
    using PAGE3_WP = SYSCFG_COMP_OPAMP_SYSCFG_RCR_PAGE3_WP_Values<SYSCFG_COMP_OPAMP::SYSCFG_RCR, 3, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_RCRBase> ;
    using PAGE4_WP = SYSCFG_COMP_OPAMP_SYSCFG_RCR_PAGE4_WP_Values<SYSCFG_COMP_OPAMP::SYSCFG_RCR, 4, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_RCRBase> ;
    using PAGE5_WP = SYSCFG_COMP_OPAMP_SYSCFG_RCR_PAGE5_WP_Values<SYSCFG_COMP_OPAMP::SYSCFG_RCR, 5, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_RCRBase> ;
    using PAGE6_WP = SYSCFG_COMP_OPAMP_SYSCFG_RCR_PAGE6_WP_Values<SYSCFG_COMP_OPAMP::SYSCFG_RCR, 6, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_RCRBase> ;
    using PAGE7_WP = SYSCFG_COMP_OPAMP_SYSCFG_RCR_PAGE7_WP_Values<SYSCFG_COMP_OPAMP::SYSCFG_RCR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_RCRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_SYSCFG_RCR_PAGE7_WP_Values<SYSCFG_COMP_OPAMP::SYSCFG_RCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_RCRPack  = Register<0x40010004, 32, ReadWriteMode, SYSCFG_COMP_OPAMPSYSCFG_RCRBase, T...> ;

  struct SYSCFG_COMP_OPAMPCOMP1_CSRBase {} ;

  struct COMP1_CSR : public RegisterBase<0x4001001C, 32, ReadWriteMode>
  {
    using COMP1EN = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1EN_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase> ;
    using COMP1_INP_DAC = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1_INP_DAC_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 1, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase> ;
    using COMP1MODE = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1MODE_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase> ;
    using COMP1INSEL = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1INSEL_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 4, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase> ;
    using COMP1_OUT_SEL = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1_OUT_SEL_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 10, 4, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase> ;
    using COMP1POL = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1POL_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 15, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase> ;
    using COMP1HYST = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1HYST_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 16, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase> ;
    using COMP1_BLANKING = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1_BLANKING_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 18, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase> ;
    using COMP1OUT = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1OUT_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 30, 1, ReadMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase> ;
    using COMP1LOCK = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1LOCK_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_COMP1_CSR_COMP1LOCK_Values<SYSCFG_COMP_OPAMP::COMP1_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using COMP1_CSRPack  = Register<0x4001001C, 32, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP1_CSRBase, T...> ;

  struct SYSCFG_COMP_OPAMPCOMP2_CSRBase {} ;

  struct COMP2_CSR : public RegisterBase<0x40010020, 32, ReadWriteMode>
  {
    using COMP2EN = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2EN_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase> ;
    using COMP2MODE = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2MODE_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase> ;
    using COMP2INSEL = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2INSEL_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 4, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase> ;
    using COMP2INPSEL = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2INPSEL_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase> ;
    using COMP2INMSEL = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2INMSEL_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 9, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase> ;
    using COMP2_OUT_SEL = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2_OUT_SEL_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 10, 4, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase> ;
    using COMP2POL = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2POL_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 15, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase> ;
    using COMP2HYST = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2HYST_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 16, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase> ;
    using COMP2_BLANKING = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2_BLANKING_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 18, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase> ;
    using COMP2LOCK = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2LOCK_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_COMP2_CSR_COMP2LOCK_Values<SYSCFG_COMP_OPAMP::COMP2_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using COMP2_CSRPack  = Register<0x40010020, 32, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP2_CSRBase, T...> ;

  struct SYSCFG_COMP_OPAMPCOMP3_CSRBase {} ;

  struct COMP3_CSR : public RegisterBase<0x40010024, 32, ReadWriteMode>
  {
    using COMP3EN = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3EN_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase> ;
    using COMP3MODE = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3MODE_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase> ;
    using COMP3INSEL = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3INSEL_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 4, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase> ;
    using COMP3INPSEL = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3INPSEL_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase> ;
    using COMP3_OUT_SEL = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3_OUT_SEL_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 10, 4, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase> ;
    using COMP3POL = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3POL_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 15, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase> ;
    using COMP3HYST = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3HYST_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 16, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase> ;
    using COMP3_BLANKING = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3_BLANKING_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 18, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase> ;
    using COMP3OUT = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3OUT_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 30, 1, ReadMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase> ;
    using COMP3LOCK = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3LOCK_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_COMP3_CSR_COMP3LOCK_Values<SYSCFG_COMP_OPAMP::COMP3_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using COMP3_CSRPack  = Register<0x40010024, 32, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP3_CSRBase, T...> ;

  struct SYSCFG_COMP_OPAMPCOMP4_CSRBase {} ;

  struct COMP4_CSR : public RegisterBase<0x40010028, 32, ReadWriteMode>
  {
    using COMP4EN = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4EN_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using COMP4MODE = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4MODE_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using COMP4INSEL = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4INSEL_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 4, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using COMP4INPSEL = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4INPSEL_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using COM4WINMODE = SYSCFG_COMP_OPAMP_COMP4_CSR_COM4WINMODE_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 9, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using COMP4_OUT_SEL = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4_OUT_SEL_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 10, 4, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using COMP4POL = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4POL_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 15, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using COMP4HYST = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4HYST_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 16, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using COMP4_BLANKING = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4_BLANKING_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 18, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using COMP4OUT = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4OUT_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 30, 1, ReadMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using COMP4LOCK = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4LOCK_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_COMP4_CSR_COMP4LOCK_Values<SYSCFG_COMP_OPAMP::COMP4_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using COMP4_CSRPack  = Register<0x40010028, 32, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP4_CSRBase, T...> ;

  struct SYSCFG_COMP_OPAMPCOMP5_CSRBase {} ;

  struct COMP5_CSR : public RegisterBase<0x4001002C, 32, ReadWriteMode>
  {
    using COMP5EN = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5EN_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase> ;
    using COMP5MODE = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5MODE_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase> ;
    using COMP5INSEL = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5INSEL_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 4, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase> ;
    using COMP5INPSEL = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5INPSEL_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase> ;
    using COMP5_OUT_SEL = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5_OUT_SEL_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 10, 4, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase> ;
    using COMP5POL = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5POL_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 15, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase> ;
    using COMP5HYST = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5HYST_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 16, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase> ;
    using COMP5_BLANKING = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5_BLANKING_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 18, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase> ;
    using COMP5OUT = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5OUT_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 30, 1, ReadMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase> ;
    using COMP5LOCK = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5LOCK_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_COMP5_CSR_COMP5LOCK_Values<SYSCFG_COMP_OPAMP::COMP5_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using COMP5_CSRPack  = Register<0x4001002C, 32, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP5_CSRBase, T...> ;

  struct SYSCFG_COMP_OPAMPCOMP6_CSRBase {} ;

  struct COMP6_CSR : public RegisterBase<0x40010030, 32, ReadWriteMode>
  {
    using COMP6EN = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6EN_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using COMP6MODE = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6MODE_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using COMP6INSEL = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6INSEL_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 4, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using COMP6INPSEL = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6INPSEL_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using COM6WINMODE = SYSCFG_COMP_OPAMP_COMP6_CSR_COM6WINMODE_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 9, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using COMP6_OUT_SEL = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6_OUT_SEL_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 10, 4, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using COMP6POL = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6POL_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 15, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using COMP6HYST = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6HYST_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 16, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using COMP6_BLANKING = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6_BLANKING_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 18, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using COMP6OUT = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6OUT_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 30, 1, ReadMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using COMP6LOCK = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6LOCK_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_COMP6_CSR_COMP6LOCK_Values<SYSCFG_COMP_OPAMP::COMP6_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using COMP6_CSRPack  = Register<0x40010030, 32, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP6_CSRBase, T...> ;

  struct SYSCFG_COMP_OPAMPCOMP7_CSRBase {} ;

  struct COMP7_CSR : public RegisterBase<0x40010034, 32, ReadWriteMode>
  {
    using COMP7EN = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7EN_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase> ;
    using COMP7MODE = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7MODE_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase> ;
    using COMP7INSEL = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7INSEL_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 4, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase> ;
    using COMP7INPSEL = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7INPSEL_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase> ;
    using COMP7_OUT_SEL = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7_OUT_SEL_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 10, 4, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase> ;
    using COMP7POL = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7POL_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 15, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase> ;
    using COMP7HYST = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7HYST_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 16, 2, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase> ;
    using COMP7_BLANKING = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7_BLANKING_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 18, 3, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase> ;
    using COMP7OUT = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7OUT_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 30, 1, ReadMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase> ;
    using COMP7LOCK = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7LOCK_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_COMP7_CSR_COMP7LOCK_Values<SYSCFG_COMP_OPAMP::COMP7_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using COMP7_CSRPack  = Register<0x40010034, 32, ReadWriteMode, SYSCFG_COMP_OPAMPCOMP7_CSRBase, T...> ;

  struct SYSCFG_COMP_OPAMPOPAMP1_CSRBase {} ;

  struct OPAMP1_CSR : public RegisterBase<0x40010038, 32, ReadWriteMode>
  {
    using OPAMP1_EN = SYSCFG_COMP_OPAMP_OPAMP1_CSR_OPAMP1_EN_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using FORCE_VP = SYSCFG_COMP_OPAMP_OPAMP1_CSR_FORCE_VP_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 1, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using VP_SEL = SYSCFG_COMP_OPAMP_OPAMP1_CSR_VP_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using VM_SEL = SYSCFG_COMP_OPAMP_OPAMP1_CSR_VM_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 5, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using TCM_EN = SYSCFG_COMP_OPAMP_OPAMP1_CSR_TCM_EN_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using VMS_SEL = SYSCFG_COMP_OPAMP_OPAMP1_CSR_VMS_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 8, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using VPS_SEL = SYSCFG_COMP_OPAMP_OPAMP1_CSR_VPS_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 9, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using CALON = SYSCFG_COMP_OPAMP_OPAMP1_CSR_CALON_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 11, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using CALSEL = SYSCFG_COMP_OPAMP_OPAMP1_CSR_CALSEL_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 12, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using PGA_GAIN = SYSCFG_COMP_OPAMP_OPAMP1_CSR_PGA_GAIN_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 14, 4, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using USER_TRIM = SYSCFG_COMP_OPAMP_OPAMP1_CSR_USER_TRIM_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 18, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using TRIMOFFSETP = SYSCFG_COMP_OPAMP_OPAMP1_CSR_TRIMOFFSETP_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 19, 5, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using TRIMOFFSETN = SYSCFG_COMP_OPAMP_OPAMP1_CSR_TRIMOFFSETN_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 24, 5, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using TSTREF = SYSCFG_COMP_OPAMP_OPAMP1_CSR_TSTREF_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 29, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using OUTCAL = SYSCFG_COMP_OPAMP_OPAMP1_CSR_OUTCAL_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 30, 1, ReadMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using LOCK = SYSCFG_COMP_OPAMP_OPAMP1_CSR_LOCK_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_OPAMP1_CSR_LOCK_Values<SYSCFG_COMP_OPAMP::OPAMP1_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OPAMP1_CSRPack  = Register<0x40010038, 32, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP1_CSRBase, T...> ;

  struct SYSCFG_COMP_OPAMPOPAMP2_CSRBase {} ;

  struct OPAMP2_CSR : public RegisterBase<0x4001003C, 32, ReadWriteMode>
  {
    using OPAMP2EN = SYSCFG_COMP_OPAMP_OPAMP2_CSR_OPAMP2EN_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using FORCE_VP = SYSCFG_COMP_OPAMP_OPAMP2_CSR_FORCE_VP_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 1, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using VP_SEL = SYSCFG_COMP_OPAMP_OPAMP2_CSR_VP_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using VM_SEL = SYSCFG_COMP_OPAMP_OPAMP2_CSR_VM_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 5, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using TCM_EN = SYSCFG_COMP_OPAMP_OPAMP2_CSR_TCM_EN_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using VMS_SEL = SYSCFG_COMP_OPAMP_OPAMP2_CSR_VMS_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 8, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using VPS_SEL = SYSCFG_COMP_OPAMP_OPAMP2_CSR_VPS_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 9, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using CALON = SYSCFG_COMP_OPAMP_OPAMP2_CSR_CALON_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 11, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using CAL_SEL = SYSCFG_COMP_OPAMP_OPAMP2_CSR_CAL_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 12, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using PGA_GAIN = SYSCFG_COMP_OPAMP_OPAMP2_CSR_PGA_GAIN_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 14, 4, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using USER_TRIM = SYSCFG_COMP_OPAMP_OPAMP2_CSR_USER_TRIM_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 18, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using TRIMOFFSETP = SYSCFG_COMP_OPAMP_OPAMP2_CSR_TRIMOFFSETP_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 19, 5, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using TRIMOFFSETN = SYSCFG_COMP_OPAMP_OPAMP2_CSR_TRIMOFFSETN_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 24, 5, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using TSTREF = SYSCFG_COMP_OPAMP_OPAMP2_CSR_TSTREF_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 29, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using OUTCAL = SYSCFG_COMP_OPAMP_OPAMP2_CSR_OUTCAL_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 30, 1, ReadMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using LOCK = SYSCFG_COMP_OPAMP_OPAMP2_CSR_LOCK_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_OPAMP2_CSR_LOCK_Values<SYSCFG_COMP_OPAMP::OPAMP2_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OPAMP2_CSRPack  = Register<0x4001003C, 32, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP2_CSRBase, T...> ;

  struct SYSCFG_COMP_OPAMPOPAMP3_CSRBase {} ;

  struct OPAMP3_CSR : public RegisterBase<0x40010040, 32, ReadWriteMode>
  {
    using OPAMP3EN = SYSCFG_COMP_OPAMP_OPAMP3_CSR_OPAMP3EN_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using FORCE_VP = SYSCFG_COMP_OPAMP_OPAMP3_CSR_FORCE_VP_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 1, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using VP_SEL = SYSCFG_COMP_OPAMP_OPAMP3_CSR_VP_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using VM_SEL = SYSCFG_COMP_OPAMP_OPAMP3_CSR_VM_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 5, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using TCM_EN = SYSCFG_COMP_OPAMP_OPAMP3_CSR_TCM_EN_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using VMS_SEL = SYSCFG_COMP_OPAMP_OPAMP3_CSR_VMS_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 8, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using VPS_SEL = SYSCFG_COMP_OPAMP_OPAMP3_CSR_VPS_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 9, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using CALON = SYSCFG_COMP_OPAMP_OPAMP3_CSR_CALON_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 11, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using CALSEL = SYSCFG_COMP_OPAMP_OPAMP3_CSR_CALSEL_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 12, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using PGA_GAIN = SYSCFG_COMP_OPAMP_OPAMP3_CSR_PGA_GAIN_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 14, 4, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using USER_TRIM = SYSCFG_COMP_OPAMP_OPAMP3_CSR_USER_TRIM_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 18, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using TRIMOFFSETP = SYSCFG_COMP_OPAMP_OPAMP3_CSR_TRIMOFFSETP_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 19, 5, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using TRIMOFFSETN = SYSCFG_COMP_OPAMP_OPAMP3_CSR_TRIMOFFSETN_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 24, 5, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using TSTREF = SYSCFG_COMP_OPAMP_OPAMP3_CSR_TSTREF_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 29, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using OUTCAL = SYSCFG_COMP_OPAMP_OPAMP3_CSR_OUTCAL_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 30, 1, ReadMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using LOCK = SYSCFG_COMP_OPAMP_OPAMP3_CSR_LOCK_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_OPAMP3_CSR_LOCK_Values<SYSCFG_COMP_OPAMP::OPAMP3_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OPAMP3_CSRPack  = Register<0x40010040, 32, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP3_CSRBase, T...> ;

  struct SYSCFG_COMP_OPAMPOPAMP4_CSRBase {} ;

  struct OPAMP4_CSR : public RegisterBase<0x40010044, 32, ReadWriteMode>
  {
    using OPAMP4EN = SYSCFG_COMP_OPAMP_OPAMP4_CSR_OPAMP4EN_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 0, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using FORCE_VP = SYSCFG_COMP_OPAMP_OPAMP4_CSR_FORCE_VP_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 1, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using VP_SEL = SYSCFG_COMP_OPAMP_OPAMP4_CSR_VP_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 2, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using VM_SEL = SYSCFG_COMP_OPAMP_OPAMP4_CSR_VM_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 5, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using TCM_EN = SYSCFG_COMP_OPAMP_OPAMP4_CSR_TCM_EN_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 7, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using VMS_SEL = SYSCFG_COMP_OPAMP_OPAMP4_CSR_VMS_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 8, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using VPS_SEL = SYSCFG_COMP_OPAMP_OPAMP4_CSR_VPS_SEL_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 9, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using CALON = SYSCFG_COMP_OPAMP_OPAMP4_CSR_CALON_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 11, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using CALSEL = SYSCFG_COMP_OPAMP_OPAMP4_CSR_CALSEL_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 12, 2, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using PGA_GAIN = SYSCFG_COMP_OPAMP_OPAMP4_CSR_PGA_GAIN_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 14, 4, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using USER_TRIM = SYSCFG_COMP_OPAMP_OPAMP4_CSR_USER_TRIM_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 18, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using TRIMOFFSETP = SYSCFG_COMP_OPAMP_OPAMP4_CSR_TRIMOFFSETP_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 19, 5, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using TRIMOFFSETN = SYSCFG_COMP_OPAMP_OPAMP4_CSR_TRIMOFFSETN_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 24, 5, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using TSTREF = SYSCFG_COMP_OPAMP_OPAMP4_CSR_TSTREF_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 29, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using OUTCAL = SYSCFG_COMP_OPAMP_OPAMP4_CSR_OUTCAL_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 30, 1, ReadMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using LOCK = SYSCFG_COMP_OPAMP_OPAMP4_CSR_LOCK_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 31, 1, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase> ;
    using FieldValues = SYSCFG_COMP_OPAMP_OPAMP4_CSR_LOCK_Values<SYSCFG_COMP_OPAMP::OPAMP4_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OPAMP4_CSRPack  = Register<0x40010044, 32, ReadWriteMode, SYSCFG_COMP_OPAMPOPAMP4_CSRBase, T...> ;

} ;

#endif //#if !defined(SYSCFGCOMPOPAMPREGISTERS_HPP)
