/*******************************************************************************
* Filename      : sysctlaregisters.hpp
*
* Details       : SYSCTL_A. This header file is auto-generated for MSP432P401Y
*                 device.
*
*
*******************************************************************************/

#if !defined(SYSCTLAREGISTERS_HPP)
#define SYSCTLAREGISTERS_HPP

#include "sysctlabitsfield.hpp"  //for Bits Fields defs 
#include "registerbase.hpp"   //for RegisterBase
#include "register.hpp"       //for Register
#include "accessmode.hpp"     //for ReadMode, WriteMode, ReadWriteMode  

struct SYSCTL_A
{
  struct SYSCTL_ASYS_REBOOT_CTLBase {} ;

  struct SYS_REBOOT_CTL : public RegisterBase<0xE0043000, 32, ReadWriteMode>
  {
    using REBOOT = SYSCTL_A_SYS_REBOOT_CTL_REBOOT_Values<SYSCTL_A::SYS_REBOOT_CTL, 0, 1, WriteMode, SYSCTL_ASYS_REBOOT_CTLBase> ;
    using WKEY = SYSCTL_A_SYS_REBOOT_CTL_WKEY_Values<SYSCTL_A::SYS_REBOOT_CTL, 8, 8, WriteMode, SYSCTL_ASYS_REBOOT_CTLBase> ;
  } ;

  template<typename... T> 
  using SYS_REBOOT_CTLPack  = Register<0xE0043000, 32, ReadWriteMode, SYSCTL_ASYS_REBOOT_CTLBase, T...> ;

  struct SYSCTL_ASYS_NMI_CTLSTATBase {} ;

  struct SYS_NMI_CTLSTAT : public RegisterBase<0xE0043004, 32, ReadWriteMode>
  {
    using CS_SRC = SYSCTL_A_SYS_NMI_CTLSTAT_CS_SRC_Values<SYSCTL_A::SYS_NMI_CTLSTAT, 0, 1, ReadWriteMode, SYSCTL_ASYS_NMI_CTLSTATBase> ;
    using PSS_SRC = SYSCTL_A_SYS_NMI_CTLSTAT_PSS_SRC_Values<SYSCTL_A::SYS_NMI_CTLSTAT, 1, 1, ReadWriteMode, SYSCTL_ASYS_NMI_CTLSTATBase> ;
    using PCM_SRC = SYSCTL_A_SYS_NMI_CTLSTAT_PCM_SRC_Values<SYSCTL_A::SYS_NMI_CTLSTAT, 2, 1, ReadWriteMode, SYSCTL_ASYS_NMI_CTLSTATBase> ;
    using PIN_SRC = SYSCTL_A_SYS_NMI_CTLSTAT_PIN_SRC_Values<SYSCTL_A::SYS_NMI_CTLSTAT, 3, 1, ReadWriteMode, SYSCTL_ASYS_NMI_CTLSTATBase> ;
    using CS_FLG = SYSCTL_A_SYS_NMI_CTLSTAT_CS_FLG_Values<SYSCTL_A::SYS_NMI_CTLSTAT, 16, 1, ReadMode, SYSCTL_ASYS_NMI_CTLSTATBase> ;
    using PSS_FLG = SYSCTL_A_SYS_NMI_CTLSTAT_PSS_FLG_Values<SYSCTL_A::SYS_NMI_CTLSTAT, 17, 1, ReadMode, SYSCTL_ASYS_NMI_CTLSTATBase> ;
    using PCM_FLG = SYSCTL_A_SYS_NMI_CTLSTAT_PCM_FLG_Values<SYSCTL_A::SYS_NMI_CTLSTAT, 18, 1, ReadMode, SYSCTL_ASYS_NMI_CTLSTATBase> ;
    using PIN_FLG = SYSCTL_A_SYS_NMI_CTLSTAT_PIN_FLG_Values<SYSCTL_A::SYS_NMI_CTLSTAT, 19, 1, ReadWriteMode, SYSCTL_ASYS_NMI_CTLSTATBase> ;
  } ;

  template<typename... T> 
  using SYS_NMI_CTLSTATPack  = Register<0xE0043004, 32, ReadWriteMode, SYSCTL_ASYS_NMI_CTLSTATBase, T...> ;

  struct SYSCTL_ASYS_WDTRESET_CTLBase {} ;

  struct SYS_WDTRESET_CTL : public RegisterBase<0xE0043008, 32, ReadWriteMode>
  {
    using TIMEOUT = SYSCTL_A_SYS_WDTRESET_CTL_TIMEOUT_Values<SYSCTL_A::SYS_WDTRESET_CTL, 0, 1, ReadWriteMode, SYSCTL_ASYS_WDTRESET_CTLBase> ;
    using VIOLATION = SYSCTL_A_SYS_WDTRESET_CTL_VIOLATION_Values<SYSCTL_A::SYS_WDTRESET_CTL, 1, 1, ReadWriteMode, SYSCTL_ASYS_WDTRESET_CTLBase> ;
  } ;

  template<typename... T> 
  using SYS_WDTRESET_CTLPack  = Register<0xE0043008, 32, ReadWriteMode, SYSCTL_ASYS_WDTRESET_CTLBase, T...> ;

  struct SYSCTL_ASYS_PERIHALT_CTLBase {} ;

  struct SYS_PERIHALT_CTL : public RegisterBase<0xE004300C, 32, ReadWriteMode>
  {
    using HALT_T16_0 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_T__Values<SYSCTL_A::SYS_PERIHALT_CTL, 0, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_T16_1 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_T__Values<SYSCTL_A::SYS_PERIHALT_CTL, 1, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_T16_2 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_T__Values<SYSCTL_A::SYS_PERIHALT_CTL, 2, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_T16_3 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_T__Values<SYSCTL_A::SYS_PERIHALT_CTL, 3, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_T32_0 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_T__Values<SYSCTL_A::SYS_PERIHALT_CTL, 4, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_eUA0 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_eUA_Values<SYSCTL_A::SYS_PERIHALT_CTL, 5, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_eUA1 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_eUA_Values<SYSCTL_A::SYS_PERIHALT_CTL, 6, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_eUA2 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_eUA_Values<SYSCTL_A::SYS_PERIHALT_CTL, 7, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_eUA3 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_eUA_Values<SYSCTL_A::SYS_PERIHALT_CTL, 8, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_eUB0 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_eUB_Values<SYSCTL_A::SYS_PERIHALT_CTL, 9, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_eUB1 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_eUB_Values<SYSCTL_A::SYS_PERIHALT_CTL, 10, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_eUB2 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_eUB_Values<SYSCTL_A::SYS_PERIHALT_CTL, 11, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_eUB3 = SYSCTL_A_SYS_PERIHALT_CTL_HALT_eUB_Values<SYSCTL_A::SYS_PERIHALT_CTL, 12, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_ADC = SYSCTL_A_SYS_PERIHALT_CTL_HALT_ADC_Values<SYSCTL_A::SYS_PERIHALT_CTL, 13, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_WDT = SYSCTL_A_SYS_PERIHALT_CTL_HALT_WDT_Values<SYSCTL_A::SYS_PERIHALT_CTL, 14, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_DMA = SYSCTL_A_SYS_PERIHALT_CTL_HALT_DMA_Values<SYSCTL_A::SYS_PERIHALT_CTL, 15, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
    using HALT_LCD = SYSCTL_A_SYS_PERIHALT_CTL_HALT_LCD_Values<SYSCTL_A::SYS_PERIHALT_CTL, 16, 1, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase> ;
  } ;

  template<typename... T> 
  using SYS_PERIHALT_CTLPack  = Register<0xE004300C, 32, ReadWriteMode, SYSCTL_ASYS_PERIHALT_CTLBase, T...> ;

  struct SYSCTL_ASYS_SRAM_SIZEBase {} ;

  struct SYS_SRAM_SIZE : public RegisterBase<0xE0043010, 32, ReadMode>
  {
    using SIZE = SYSCTL_A_SYS_SRAM_SIZE_SIZE_Values<SYSCTL_A::SYS_SRAM_SIZE, 0, 32, ReadMode, SYSCTL_ASYS_SRAM_SIZEBase> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_SIZEPack  = Register<0xE0043010, 32, ReadMode, SYSCTL_ASYS_SRAM_SIZEBase, T...> ;

  struct SYSCTL_ASYS_SRAM_NUMBANKSBase {} ;

  struct SYS_SRAM_NUMBANKS : public RegisterBase<0xE0043014, 32, ReadMode>
  {
    using NUM = SYSCTL_A_SYS_SRAM_NUMBANKS_NUM_Values<SYSCTL_A::SYS_SRAM_NUMBANKS, 0, 32, ReadMode, SYSCTL_ASYS_SRAM_NUMBANKSBase> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_NUMBANKSPack  = Register<0xE0043014, 32, ReadMode, SYSCTL_ASYS_SRAM_NUMBANKSBase, T...> ;

  struct SYSCTL_ASYS_SRAM_NUMBLOCKSBase {} ;

  struct SYS_SRAM_NUMBLOCKS : public RegisterBase<0xE0043018, 32, ReadMode>
  {
    using NUM = SYSCTL_A_SYS_SRAM_NUMBLOCKS_NUM_Values<SYSCTL_A::SYS_SRAM_NUMBLOCKS, 0, 32, ReadMode, SYSCTL_ASYS_SRAM_NUMBLOCKSBase> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_NUMBLOCKSPack  = Register<0xE0043018, 32, ReadMode, SYSCTL_ASYS_SRAM_NUMBLOCKSBase, T...> ;

  struct SYSCTL_ASYS_MAINFLASH_SIZEBase {} ;

  struct SYS_MAINFLASH_SIZE : public RegisterBase<0xE0043020, 32, ReadMode>
  {
    using SIZE = SYSCTL_A_SYS_MAINFLASH_SIZE_SIZE_Values<SYSCTL_A::SYS_MAINFLASH_SIZE, 0, 32, ReadMode, SYSCTL_ASYS_MAINFLASH_SIZEBase> ;
  } ;

  template<typename... T> 
  using SYS_MAINFLASH_SIZEPack  = Register<0xE0043020, 32, ReadMode, SYSCTL_ASYS_MAINFLASH_SIZEBase, T...> ;

  struct SYSCTL_ASYS_INFOFLASH_SIZEBase {} ;

  struct SYS_INFOFLASH_SIZE : public RegisterBase<0xE0043024, 32, ReadMode>
  {
    using SIZE = SYSCTL_A_SYS_INFOFLASH_SIZE_SIZE_Values<SYSCTL_A::SYS_INFOFLASH_SIZE, 0, 32, ReadMode, SYSCTL_ASYS_INFOFLASH_SIZEBase> ;
  } ;

  template<typename... T> 
  using SYS_INFOFLASH_SIZEPack  = Register<0xE0043024, 32, ReadMode, SYSCTL_ASYS_INFOFLASH_SIZEBase, T...> ;

  struct SYSCTL_ASYS_DIO_GLTFLT_CTLBase {} ;

  struct SYS_DIO_GLTFLT_CTL : public RegisterBase<0xE0043030, 32, ReadWriteMode>
  {
    using GLTCH_EN = SYSCTL_A_SYS_DIO_GLTFLT_CTL_GLTCH_EN_Values<SYSCTL_A::SYS_DIO_GLTFLT_CTL, 0, 1, ReadWriteMode, SYSCTL_ASYS_DIO_GLTFLT_CTLBase> ;
  } ;

  template<typename... T> 
  using SYS_DIO_GLTFLT_CTLPack  = Register<0xE0043030, 32, ReadWriteMode, SYSCTL_ASYS_DIO_GLTFLT_CTLBase, T...> ;

  struct SYSCTL_ASYS_SECDATA_UNLOCKBase {} ;

  struct SYS_SECDATA_UNLOCK : public RegisterBase<0xE0043040, 32, ReadWriteMode>
  {
    using UNLKEY = SYSCTL_A_SYS_SECDATA_UNLOCK_UNLKEY_Values<SYSCTL_A::SYS_SECDATA_UNLOCK, 0, 16, ReadWriteMode, SYSCTL_ASYS_SECDATA_UNLOCKBase> ;
  } ;

  template<typename... T> 
  using SYS_SECDATA_UNLOCKPack  = Register<0xE0043040, 32, ReadWriteMode, SYSCTL_ASYS_SECDATA_UNLOCKBase, T...> ;

  struct SYSCTL_ASYS_SRAM_BANKEN_CTL0Base {} ;

  struct SYS_SRAM_BANKEN_CTL0 : public RegisterBase<0xE0043050, 32, ReadWriteMode>
  {
    using BNK0_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 0, 1, ReadMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK1_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 1, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK2_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 2, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK3_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 3, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK4_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 4, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK5_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 5, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK6_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 6, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK7_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 7, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK8_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 8, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK9_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 9, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK10_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 10, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK11_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 11, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK12_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 12, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK13_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 13, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK14_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 14, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK15_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 15, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK16_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 16, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK17_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 17, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK18_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 18, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK19_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 19, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK20_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 20, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK21_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 21, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK22_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 22, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK23_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 23, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK24_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 24, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK25_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 25, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK26_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 26, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK27_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 27, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK28_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 28, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK29_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 29, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK30_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 30, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
    using BNK31_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL0, 31, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_BANKEN_CTL0Pack  = Register<0xE0043050, 32, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL0Base, T...> ;

  struct SYSCTL_ASYS_SRAM_BANKEN_CTL1Base {} ;

  struct SYS_SRAM_BANKEN_CTL1 : public RegisterBase<0xE0043054, 32, ReadWriteMode>
  {
    using BNK32_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 0, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK33_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 1, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK34_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 2, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK35_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 3, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK36_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 4, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK37_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 5, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK38_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 6, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK39_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 7, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK40_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 8, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK41_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 9, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK42_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 10, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK43_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 11, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK44_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 12, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK45_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 13, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK46_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 14, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK47_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 15, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK48_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 16, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK49_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 17, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK50_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 18, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK51_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 19, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK52_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 20, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK53_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 21, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK54_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 22, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK55_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 23, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK56_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 24, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK57_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 25, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK58_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 26, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK59_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 27, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK60_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 28, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK61_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 29, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK62_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 30, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
    using BNK63_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL1, 31, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_BANKEN_CTL1Pack  = Register<0xE0043054, 32, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL1Base, T...> ;

  struct SYSCTL_ASYS_SRAM_BANKEN_CTL2Base {} ;

  struct SYS_SRAM_BANKEN_CTL2 : public RegisterBase<0xE0043058, 32, ReadWriteMode>
  {
    using BNK64_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 0, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK65_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 1, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK66_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 2, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK67_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 3, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK68_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 4, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK69_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 5, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK70_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 6, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK71_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 7, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK72_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 8, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK73_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 9, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK74_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 10, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK75_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 11, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK76_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 12, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK77_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 13, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK78_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 14, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK79_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 15, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK80_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 16, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK81_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 17, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK82_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 18, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK83_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 19, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK84_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 20, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK85_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 21, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK86_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 22, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK87_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 23, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK88_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 24, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK89_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 25, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK90_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 26, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK91_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 27, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK92_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 28, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK93_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 29, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK94_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 30, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
    using BNK95_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL2, 31, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_BANKEN_CTL2Pack  = Register<0xE0043058, 32, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL2Base, T...> ;

  struct SYSCTL_ASYS_SRAM_BANKEN_CTL3Base {} ;

  struct SYS_SRAM_BANKEN_CTL3 : public RegisterBase<0xE004305C, 32, ReadWriteMode>
  {
    using BNK96_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 0, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK97_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 1, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK98_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 2, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK99_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 3, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK100_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 4, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK101_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 5, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK102_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 6, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK103_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 7, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK104_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 8, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK105_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 9, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK106_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 10, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK107_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 11, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK108_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 12, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK109_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 13, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK110_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 14, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK111_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 15, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK112_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 16, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK113_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 17, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK114_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 18, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK115_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 19, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK116_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 20, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK117_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 21, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK118_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 22, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK119_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 23, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK120_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 24, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK121_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 25, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK122_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 26, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK123_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 27, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK124_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 28, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK125_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 29, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK126_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 30, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
    using BNK127_EN = SYSCTL_A_SYS_SRAM_BANKEN_CTL_BNK_EN_Values<SYSCTL_A::SYS_SRAM_BANKEN_CTL3, 31, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_BANKEN_CTL3Pack  = Register<0xE004305C, 32, ReadWriteMode, SYSCTL_ASYS_SRAM_BANKEN_CTL3Base, T...> ;

  struct SYSCTL_ASYS_SRAM_BLKRET_CTL0Base {} ;

  struct SYS_SRAM_BLKRET_CTL0 : public RegisterBase<0xE0043070, 32, ReadWriteMode>
  {
    using BLK0_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 0, 1, ReadMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK1_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 1, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK2_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 2, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK3_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 3, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK4_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 4, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK5_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 5, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK6_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 6, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK7_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 7, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK8_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 8, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK9_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 9, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK10_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 10, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK11_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 11, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK12_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 12, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK13_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 13, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK14_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 14, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK15_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 15, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK16_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 16, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK17_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 17, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK18_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 18, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK19_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 19, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK20_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 20, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK21_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 21, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK22_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 22, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK23_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 23, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK24_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 24, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK25_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 25, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK26_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 26, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK27_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 27, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK28_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 28, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK29_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 29, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK30_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 30, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
    using BLK31_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL0, 31, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_BLKRET_CTL0Pack  = Register<0xE0043070, 32, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL0Base, T...> ;

  struct SYSCTL_ASYS_SRAM_BLKRET_CTL1Base {} ;

  struct SYS_SRAM_BLKRET_CTL1 : public RegisterBase<0xE0043074, 32, ReadWriteMode>
  {
    using BLK32_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 0, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK33_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 1, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK34_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 2, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK35_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 3, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK36_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 4, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK37_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 5, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK38_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 6, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK39_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 7, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK40_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 8, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK41_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 9, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK42_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 10, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK43_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 11, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK44_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 12, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK45_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 13, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK46_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 14, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK47_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 15, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK48_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 16, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK49_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 17, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK50_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 18, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK51_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 19, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK52_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 20, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK53_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 21, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK54_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 22, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK55_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 23, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK56_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 24, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK57_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 25, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK58_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 26, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK59_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 27, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK60_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 28, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK61_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 29, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK62_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 30, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
    using BLK63_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL1, 31, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_BLKRET_CTL1Pack  = Register<0xE0043074, 32, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL1Base, T...> ;

  struct SYSCTL_ASYS_SRAM_BLKRET_CTL2Base {} ;

  struct SYS_SRAM_BLKRET_CTL2 : public RegisterBase<0xE0043078, 32, ReadWriteMode>
  {
    using BLK64_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 0, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK65_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 1, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK66_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 2, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK67_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 3, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK68_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 4, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK69_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 5, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK70_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 6, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK71_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 7, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK72_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 8, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK73_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 9, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK74_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 10, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK75_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 11, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK76_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 12, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK77_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 13, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK78_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 14, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK79_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 15, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK80_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 16, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK81_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 17, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK82_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 18, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK83_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 19, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK84_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 20, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK85_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 21, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK86_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 22, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK87_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 23, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK88_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 24, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK89_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 25, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK90_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 26, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK91_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 27, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK92_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 28, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK93_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 29, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK94_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 30, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
    using BLK95_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL2, 31, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_BLKRET_CTL2Pack  = Register<0xE0043078, 32, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL2Base, T...> ;

  struct SYSCTL_ASYS_SRAM_BLKRET_CTL3Base {} ;

  struct SYS_SRAM_BLKRET_CTL3 : public RegisterBase<0xE004307C, 32, ReadWriteMode>
  {
    using BLK96_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 0, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK97_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 1, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK98_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 2, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK99_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 3, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK100_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 4, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK101_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 5, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK102_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 6, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK103_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 7, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK104_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 8, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK105_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 9, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK106_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 10, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK107_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 11, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK108_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 12, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK109_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 13, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK110_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 14, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK111_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 15, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK112_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 16, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK113_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 17, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK114_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 18, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK115_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 19, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK116_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 20, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK117_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 21, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK118_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 22, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK119_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 23, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK120_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 24, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK121_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 25, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK122_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 26, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK123_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 27, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK124_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 28, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK125_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 29, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK126_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 30, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
    using BLK127_EN = SYSCTL_A_SYS_SRAM_BLKRET_CTL_BLK_EN_Values<SYSCTL_A::SYS_SRAM_BLKRET_CTL3, 31, 1, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_BLKRET_CTL3Pack  = Register<0xE004307C, 32, ReadWriteMode, SYSCTL_ASYS_SRAM_BLKRET_CTL3Base, T...> ;

  struct SYSCTL_ASYS_SRAM_STATBase {} ;

  struct SYS_SRAM_STAT : public RegisterBase<0xE0043090, 32, ReadMode>
  {
    using BNKEN_RDY = SYSCTL_A_SYS_SRAM_STAT_BNKEN_RDY_Values<SYSCTL_A::SYS_SRAM_STAT, 0, 1, ReadMode, SYSCTL_ASYS_SRAM_STATBase> ;
    using BLKRET_RDY = SYSCTL_A_SYS_SRAM_STAT_BLKRET_RDY_Values<SYSCTL_A::SYS_SRAM_STAT, 1, 1, ReadMode, SYSCTL_ASYS_SRAM_STATBase> ;
  } ;

  template<typename... T> 
  using SYS_SRAM_STATPack  = Register<0xE0043090, 32, ReadMode, SYSCTL_ASYS_SRAM_STATBase, T...> ;

  struct SYSCTL_ASYS_MASTER_UNLOCKBase {} ;

  struct SYS_MASTER_UNLOCK : public RegisterBase<0xE0044000, 32, ReadWriteMode>
  {
    using UNLKEY = SYSCTL_A_SYS_MASTER_UNLOCK_UNLKEY_Values<SYSCTL_A::SYS_MASTER_UNLOCK, 0, 16, ReadWriteMode, SYSCTL_ASYS_MASTER_UNLOCKBase> ;
  } ;

  template<typename... T> 
  using SYS_MASTER_UNLOCKPack  = Register<0xE0044000, 32, ReadWriteMode, SYSCTL_ASYS_MASTER_UNLOCKBase, T...> ;

  struct SYSCTL_ASYS_BOOTOVER_ACKBase {} ;

  struct SYS_BOOTOVER_ACK : public RegisterBase<0xE004400C, 32, ReadWriteMode>
  {
    using REGVAL = SYSCTL_A_SYS_BOOTOVER_ACK_REGVAL_Values<SYSCTL_A::SYS_BOOTOVER_ACK, 0, 32, ReadWriteMode, SYSCTL_ASYS_BOOTOVER_ACKBase> ;
  } ;

  template<typename... T> 
  using SYS_BOOTOVER_ACKPack  = Register<0xE004400C, 32, ReadWriteMode, SYSCTL_ASYS_BOOTOVER_ACKBase, T...> ;

  struct SYSCTL_ASYS_RESET_REQBase {} ;

  struct SYS_RESET_REQ : public RegisterBase<0xE0044010, 32, ReadWriteMode>
  {
    using POR = SYSCTL_A_SYS_RESET_REQ_POR_Values<SYSCTL_A::SYS_RESET_REQ, 0, 1, WriteMode, SYSCTL_ASYS_RESET_REQBase> ;
    using REBOOT = SYSCTL_A_SYS_RESET_REQ_REBOOT_Values<SYSCTL_A::SYS_RESET_REQ, 1, 1, WriteMode, SYSCTL_ASYS_RESET_REQBase> ;
    using WKEY = SYSCTL_A_SYS_RESET_REQ_WKEY_Values<SYSCTL_A::SYS_RESET_REQ, 8, 8, WriteMode, SYSCTL_ASYS_RESET_REQBase> ;
  } ;

  template<typename... T> 
  using SYS_RESET_REQPack  = Register<0xE0044010, 32, ReadWriteMode, SYSCTL_ASYS_RESET_REQBase, T...> ;

  struct SYSCTL_ASYS_RESET_STATOVERBase {} ;

  struct SYS_RESET_STATOVER : public RegisterBase<0xE0044014, 32, ReadWriteMode>
  {
    using SOFT = SYSCTL_A_SYS_RESET_STATOVER_SOFT_Values<SYSCTL_A::SYS_RESET_STATOVER, 0, 1, ReadMode, SYSCTL_ASYS_RESET_STATOVERBase> ;
    using HARD = SYSCTL_A_SYS_RESET_STATOVER_HARD_Values<SYSCTL_A::SYS_RESET_STATOVER, 1, 1, ReadMode, SYSCTL_ASYS_RESET_STATOVERBase> ;
    using REBOOT = SYSCTL_A_SYS_RESET_STATOVER_REBOOT_Values<SYSCTL_A::SYS_RESET_STATOVER, 2, 1, ReadMode, SYSCTL_ASYS_RESET_STATOVERBase> ;
    using SOFT_OVER = SYSCTL_A_SYS_RESET_STATOVER_SOFT_OVER_Values<SYSCTL_A::SYS_RESET_STATOVER, 8, 1, ReadWriteMode, SYSCTL_ASYS_RESET_STATOVERBase> ;
    using HARD_OVER = SYSCTL_A_SYS_RESET_STATOVER_HARD_OVER_Values<SYSCTL_A::SYS_RESET_STATOVER, 9, 1, ReadWriteMode, SYSCTL_ASYS_RESET_STATOVERBase> ;
    using RBT_OVER = SYSCTL_A_SYS_RESET_STATOVER_RBT_OVER_Values<SYSCTL_A::SYS_RESET_STATOVER, 10, 1, ReadWriteMode, SYSCTL_ASYS_RESET_STATOVERBase> ;
  } ;

  template<typename... T> 
  using SYS_RESET_STATOVERPack  = Register<0xE0044014, 32, ReadWriteMode, SYSCTL_ASYS_RESET_STATOVERBase, T...> ;

  struct SYSCTL_ASYS_SYSTEM_STATBase {} ;

  struct SYS_SYSTEM_STAT : public RegisterBase<0xE0044020, 32, ReadMode>
  {
    using DBG_SEC_ACT = SYSCTL_A_SYS_SYSTEM_STAT_DBG_SEC_ACT_Values<SYSCTL_A::SYS_SYSTEM_STAT, 3, 1, ReadMode, SYSCTL_ASYS_SYSTEM_STATBase> ;
    using JTAG_SWD_LOCK_ACT = SYSCTL_A_SYS_SYSTEM_STAT_JTAG_SWD_LOCK_ACT_Values<SYSCTL_A::SYS_SYSTEM_STAT, 4, 1, ReadMode, SYSCTL_ASYS_SYSTEM_STATBase> ;
    using IP_PROT_ACT = SYSCTL_A_SYS_SYSTEM_STAT_IP_PROT_ACT_Values<SYSCTL_A::SYS_SYSTEM_STAT, 5, 1, ReadMode, SYSCTL_ASYS_SYSTEM_STATBase> ;
  } ;

  template<typename... T> 
  using SYS_SYSTEM_STATPack  = Register<0xE0044020, 32, ReadMode, SYSCTL_ASYS_SYSTEM_STATBase, T...> ;

  struct SYSCTL_ASYS_BOOTOVER_REQ0Base {} ;

  struct SYS_BOOTOVER_REQ0 : public RegisterBase<0xE0044004, 32, ReadWriteMode>
  {
    using REGVAL = SYSCTL_A_SYS_BOOTOVER_REQ_REGVAL_Values<SYSCTL_A::SYS_BOOTOVER_REQ0, 0, 32, ReadWriteMode, SYSCTL_ASYS_BOOTOVER_REQ0Base> ;
  } ;

  template<typename... T> 
  using SYS_BOOTOVER_REQ0Pack  = Register<0xE0044004, 32, ReadWriteMode, SYSCTL_ASYS_BOOTOVER_REQ0Base, T...> ;

  struct SYSCTL_ASYS_BOOTOVER_REQ1Base {} ;

  struct SYS_BOOTOVER_REQ1 : public RegisterBase<0xE0044008, 32, ReadWriteMode>
  {
    using REGVAL = SYSCTL_A_SYS_BOOTOVER_REQ_REGVAL_Values<SYSCTL_A::SYS_BOOTOVER_REQ1, 0, 32, ReadWriteMode, SYSCTL_ASYS_BOOTOVER_REQ1Base> ;
  } ;

  template<typename... T> 
  using SYS_BOOTOVER_REQ1Pack  = Register<0xE0044008, 32, ReadWriteMode, SYSCTL_ASYS_BOOTOVER_REQ1Base, T...> ;

} ;

#endif //#if !defined(SYSCTLAREGISTERS_HPP)
