/*******************************************************************************
* Filename      : otghsglobalregisters.hpp
*
* Details       : USB on the go high speed. This header file is auto-generated
*                 for STM32F407 device.
*
*
*******************************************************************************/

#if !defined(OTGHSGLOBALREGISTERS_HPP)
#define OTGHSGLOBALREGISTERS_HPP

#include "otghsglobalfieldvalues.hpp"  //for Bits Fields defs 
#include "registerbase.hpp"   //for RegisterBase
#include "register.hpp"       //for Register
#include "accessmode.hpp"     //for ReadMode, WriteMode, ReadWriteMode  

struct OTG_HS_GLOBAL
{
  struct OTG_HS_GLOBALOTG_HS_GOTGCTLBase {} ;

  struct OTG_HS_GOTGCTL : public RegisterBase<0x40040000, 32, ReadWriteMode>
  {
    using SRQSCS = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_SRQSCS_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 0, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using SRQ = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_SRQ_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 1, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using HNGSCS = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_HNGSCS_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 8, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using HNPRQ = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_HNPRQ_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 9, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using HSHNPEN = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_HSHNPEN_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 10, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using DHNPEN = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_DHNPEN_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 11, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using CIDSTS = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_CIDSTS_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 16, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using DBCT = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_DBCT_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 17, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using ASVLD = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_ASVLD_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 18, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using BSVLD = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_BSVLD_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 19, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GOTGCTL_BSVLD_Values<OTG_HS_GLOBAL::OTG_HS_GOTGCTL, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GOTGCTLPack  = Register<0x40040000, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGCTLBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GOTGINTBase {} ;

  struct OTG_HS_GOTGINT : public RegisterBase<0x40040004, 32, ReadWriteMode>
  {
    using SEDET = OTG_HS_GLOBAL_OTG_HS_GOTGINT_SEDET_Values<OTG_HS_GLOBAL::OTG_HS_GOTGINT, 2, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using SRSSCHG = OTG_HS_GLOBAL_OTG_HS_GOTGINT_SRSSCHG_Values<OTG_HS_GLOBAL::OTG_HS_GOTGINT, 8, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using HNSSCHG = OTG_HS_GLOBAL_OTG_HS_GOTGINT_HNSSCHG_Values<OTG_HS_GLOBAL::OTG_HS_GOTGINT, 9, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using HNGDET = OTG_HS_GLOBAL_OTG_HS_GOTGINT_HNGDET_Values<OTG_HS_GLOBAL::OTG_HS_GOTGINT, 17, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using ADTOCHG = OTG_HS_GLOBAL_OTG_HS_GOTGINT_ADTOCHG_Values<OTG_HS_GLOBAL::OTG_HS_GOTGINT, 18, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using DBCDNE = OTG_HS_GLOBAL_OTG_HS_GOTGINT_DBCDNE_Values<OTG_HS_GLOBAL::OTG_HS_GOTGINT, 19, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GOTGINT_DBCDNE_Values<OTG_HS_GLOBAL::OTG_HS_GOTGINT, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GOTGINTPack  = Register<0x40040004, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GOTGINTBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GAHBCFGBase {} ;

  struct OTG_HS_GAHBCFG : public RegisterBase<0x40040008, 32, ReadWriteMode>
  {
    using GINT = OTG_HS_GLOBAL_OTG_HS_GAHBCFG_GINT_Values<OTG_HS_GLOBAL::OTG_HS_GAHBCFG, 0, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GAHBCFGBase> ;
    using HBSTLEN = OTG_HS_GLOBAL_OTG_HS_GAHBCFG_HBSTLEN_Values<OTG_HS_GLOBAL::OTG_HS_GAHBCFG, 1, 4, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GAHBCFGBase> ;
    using DMAEN = OTG_HS_GLOBAL_OTG_HS_GAHBCFG_DMAEN_Values<OTG_HS_GLOBAL::OTG_HS_GAHBCFG, 5, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GAHBCFGBase> ;
    using TXFELVL = OTG_HS_GLOBAL_OTG_HS_GAHBCFG_TXFELVL_Values<OTG_HS_GLOBAL::OTG_HS_GAHBCFG, 7, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GAHBCFGBase> ;
    using PTXFELVL = OTG_HS_GLOBAL_OTG_HS_GAHBCFG_PTXFELVL_Values<OTG_HS_GLOBAL::OTG_HS_GAHBCFG, 8, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GAHBCFGBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GAHBCFG_PTXFELVL_Values<OTG_HS_GLOBAL::OTG_HS_GAHBCFG, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GAHBCFGPack  = Register<0x40040008, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GAHBCFGBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GUSBCFGBase {} ;

  struct OTG_HS_GUSBCFG : public RegisterBase<0x4004000C, 32, ReadWriteMode>
  {
    using TOCAL = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_TOCAL_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 0, 3, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using PHYSEL = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_PHYSEL_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 6, 1, WriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using SRPCAP = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_SRPCAP_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 8, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using HNPCAP = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_HNPCAP_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 9, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using TRDT = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_TRDT_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 10, 4, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using PHYLPCS = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_PHYLPCS_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 15, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPIFSLS = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIFSLS_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 17, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPIAR = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIAR_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 18, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPICSM = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_ULPICSM_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 19, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPIEVBUSD = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIEVBUSD_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 20, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPIEVBUSI = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIEVBUSI_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 21, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using TSDPS = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_TSDPS_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 22, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using PCCI = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_PCCI_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 23, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using PTCI = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_PTCI_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 24, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPIIPD = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIIPD_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 25, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using FHMOD = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_FHMOD_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 29, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using FDMOD = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_FDMOD_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 30, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using CTXPKT = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_CTXPKT_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 31, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GUSBCFG_CTXPKT_Values<OTG_HS_GLOBAL::OTG_HS_GUSBCFG, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GUSBCFGPack  = Register<0x4004000C, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GUSBCFGBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GRSTCTLBase {} ;

  struct OTG_HS_GRSTCTL : public RegisterBase<0x40040010, 32, ReadWriteMode>
  {
    using CSRST = OTG_HS_GLOBAL_OTG_HS_GRSTCTL_CSRST_Values<OTG_HS_GLOBAL::OTG_HS_GRSTCTL, 0, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using HSRST = OTG_HS_GLOBAL_OTG_HS_GRSTCTL_HSRST_Values<OTG_HS_GLOBAL::OTG_HS_GRSTCTL, 1, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using FCRST = OTG_HS_GLOBAL_OTG_HS_GRSTCTL_FCRST_Values<OTG_HS_GLOBAL::OTG_HS_GRSTCTL, 2, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using RXFFLSH = OTG_HS_GLOBAL_OTG_HS_GRSTCTL_RXFFLSH_Values<OTG_HS_GLOBAL::OTG_HS_GRSTCTL, 4, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using TXFFLSH = OTG_HS_GLOBAL_OTG_HS_GRSTCTL_TXFFLSH_Values<OTG_HS_GLOBAL::OTG_HS_GRSTCTL, 5, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using TXFNUM = OTG_HS_GLOBAL_OTG_HS_GRSTCTL_TXFNUM_Values<OTG_HS_GLOBAL::OTG_HS_GRSTCTL, 6, 5, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using DMAREQ = OTG_HS_GLOBAL_OTG_HS_GRSTCTL_DMAREQ_Values<OTG_HS_GLOBAL::OTG_HS_GRSTCTL, 30, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using AHBIDL = OTG_HS_GLOBAL_OTG_HS_GRSTCTL_AHBIDL_Values<OTG_HS_GLOBAL::OTG_HS_GRSTCTL, 31, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GRSTCTL_AHBIDL_Values<OTG_HS_GLOBAL::OTG_HS_GRSTCTL, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRSTCTLPack  = Register<0x40040010, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GRSTCTLBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GINTSTSBase {} ;

  struct OTG_HS_GINTSTS : public RegisterBase<0x40040014, 32, ReadWriteMode>
  {
    using CMOD = OTG_HS_GLOBAL_OTG_HS_GINTSTS_CMOD_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 0, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using MMIS = OTG_HS_GLOBAL_OTG_HS_GINTSTS_MMIS_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 1, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using OTGINT = OTG_HS_GLOBAL_OTG_HS_GINTSTS_OTGINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 2, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using SOF = OTG_HS_GLOBAL_OTG_HS_GINTSTS_SOF_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 3, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using RXFLVL = OTG_HS_GLOBAL_OTG_HS_GINTSTS_RXFLVL_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 4, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using NPTXFE = OTG_HS_GLOBAL_OTG_HS_GINTSTS_NPTXFE_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 5, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using GINAKEFF = OTG_HS_GLOBAL_OTG_HS_GINTSTS_GINAKEFF_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 6, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using BOUTNAKEFF = OTG_HS_GLOBAL_OTG_HS_GINTSTS_BOUTNAKEFF_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 7, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using ESUSP = OTG_HS_GLOBAL_OTG_HS_GINTSTS_ESUSP_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 10, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using USBSUSP = OTG_HS_GLOBAL_OTG_HS_GINTSTS_USBSUSP_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 11, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using USBRST = OTG_HS_GLOBAL_OTG_HS_GINTSTS_USBRST_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 12, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using ENUMDNE = OTG_HS_GLOBAL_OTG_HS_GINTSTS_ENUMDNE_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 13, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using ISOODRP = OTG_HS_GLOBAL_OTG_HS_GINTSTS_ISOODRP_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 14, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using EOPF = OTG_HS_GLOBAL_OTG_HS_GINTSTS_EOPF_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 15, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using IEPINT = OTG_HS_GLOBAL_OTG_HS_GINTSTS_IEPINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 18, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using OEPINT = OTG_HS_GLOBAL_OTG_HS_GINTSTS_OEPINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 19, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using IISOIXFR = OTG_HS_GLOBAL_OTG_HS_GINTSTS_IISOIXFR_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 20, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using PXFR_INCOMPISOOUT = OTG_HS_GLOBAL_OTG_HS_GINTSTS_PXFR_INCOMPISOOUT_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 21, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using DATAFSUSP = OTG_HS_GLOBAL_OTG_HS_GINTSTS_DATAFSUSP_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 22, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using HPRTINT = OTG_HS_GLOBAL_OTG_HS_GINTSTS_HPRTINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 24, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using HCINT = OTG_HS_GLOBAL_OTG_HS_GINTSTS_HCINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 25, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using PTXFE = OTG_HS_GLOBAL_OTG_HS_GINTSTS_PTXFE_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 26, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using CIDSCHG = OTG_HS_GLOBAL_OTG_HS_GINTSTS_CIDSCHG_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 28, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using DISCINT = OTG_HS_GLOBAL_OTG_HS_GINTSTS_DISCINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 29, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using SRQINT = OTG_HS_GLOBAL_OTG_HS_GINTSTS_SRQINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 30, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using WKUINT = OTG_HS_GLOBAL_OTG_HS_GINTSTS_WKUINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 31, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GINTSTS_WKUINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTSTS, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GINTSTSPack  = Register<0x40040014, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTSTSBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GINTMSKBase {} ;

  struct OTG_HS_GINTMSK : public RegisterBase<0x40040018, 32, ReadWriteMode>
  {
    using MMISM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_MMISM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 1, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using OTGINT = OTG_HS_GLOBAL_OTG_HS_GINTMSK_OTGINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 2, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using SOFM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_SOFM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 3, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using RXFLVLM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_RXFLVLM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 4, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using NPTXFEM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_NPTXFEM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 5, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using GINAKEFFM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_GINAKEFFM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 6, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using GONAKEFFM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_GONAKEFFM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 7, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using ESUSPM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_ESUSPM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 10, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using USBSUSPM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_USBSUSPM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 11, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using USBRST = OTG_HS_GLOBAL_OTG_HS_GINTMSK_USBRST_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 12, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using ENUMDNEM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_ENUMDNEM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 13, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using ISOODRPM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_ISOODRPM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 14, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using EOPFM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_EOPFM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 15, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using EPMISM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_EPMISM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 17, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using IEPINT = OTG_HS_GLOBAL_OTG_HS_GINTMSK_IEPINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 18, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using OEPINT = OTG_HS_GLOBAL_OTG_HS_GINTMSK_OEPINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 19, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using IISOIXFRM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_IISOIXFRM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 20, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using PXFRM_IISOOXFRM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_PXFRM_IISOOXFRM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 21, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using FSUSPM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_FSUSPM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 22, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using PRTIM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_PRTIM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 24, 1, ReadMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using HCIM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_HCIM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 25, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using PTXFEM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_PTXFEM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 26, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using CIDSCHGM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_CIDSCHGM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 28, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using DISCINT = OTG_HS_GLOBAL_OTG_HS_GINTMSK_DISCINT_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 29, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using SRQIM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_SRQIM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 30, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using WUIM = OTG_HS_GLOBAL_OTG_HS_GINTMSK_WUIM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 31, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GINTMSK_WUIM_Values<OTG_HS_GLOBAL::OTG_HS_GINTMSK, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GINTMSKPack  = Register<0x40040018, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GINTMSKBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GRXSTSR_HostBase {} ;

  struct OTG_HS_GRXSTSR_Host : public RegisterBase<0x4004001C, 32, ReadMode>
  {
    using CHNUM = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Host_CHNUM_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Host, 0, 4, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_HostBase> ;
    using BCNT = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Host_BCNT_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Host, 4, 11, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_HostBase> ;
    using DPID = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Host_DPID_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Host, 15, 2, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_HostBase> ;
    using PKTSTS = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Host_PKTSTS_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Host, 17, 4, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_HostBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Host_PKTSTS_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Host, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRXSTSR_HostPack  = Register<0x4004001C, 32, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_HostBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GRXSTSP_HostBase {} ;

  struct OTG_HS_GRXSTSP_Host : public RegisterBase<0x40040020, 32, ReadMode>
  {
    using CHNUM = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Host_CHNUM_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Host, 0, 4, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_HostBase> ;
    using BCNT = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Host_BCNT_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Host, 4, 11, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_HostBase> ;
    using DPID = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Host_DPID_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Host, 15, 2, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_HostBase> ;
    using PKTSTS = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Host_PKTSTS_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Host, 17, 4, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_HostBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Host_PKTSTS_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Host, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRXSTSP_HostPack  = Register<0x40040020, 32, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_HostBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GRXFSIZBase {} ;

  struct OTG_HS_GRXFSIZ : public RegisterBase<0x40040024, 32, ReadWriteMode>
  {
    using RXFD = OTG_HS_GLOBAL_OTG_HS_GRXFSIZ_RXFD_Values<OTG_HS_GLOBAL::OTG_HS_GRXFSIZ, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GRXFSIZBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GRXFSIZ_RXFD_Values<OTG_HS_GLOBAL::OTG_HS_GRXFSIZ, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRXFSIZPack  = Register<0x40040024, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GRXFSIZBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GNPTXFSIZ_HostBase {} ;

  struct OTG_HS_GNPTXFSIZ_Host : public RegisterBase<0x40040028, 32, ReadWriteMode>
  {
    using NPTXFSA = OTG_HS_GLOBAL_OTG_HS_GNPTXFSIZ_Host_NPTXFSA_Values<OTG_HS_GLOBAL::OTG_HS_GNPTXFSIZ_Host, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GNPTXFSIZ_HostBase> ;
    using NPTXFD = OTG_HS_GLOBAL_OTG_HS_GNPTXFSIZ_Host_NPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_GNPTXFSIZ_Host, 16, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GNPTXFSIZ_HostBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GNPTXFSIZ_Host_NPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_GNPTXFSIZ_Host, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GNPTXFSIZ_HostPack  = Register<0x40040028, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GNPTXFSIZ_HostBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_TX0FSIZ_PeripheralBase {} ;

  struct OTG_HS_TX0FSIZ_Peripheral : public RegisterBase<0x40040028, 32, ReadWriteMode>
  {
    using TX0FSA = OTG_HS_GLOBAL_OTG_HS_TX0FSIZ_Peripheral_TX0FSA_Values<OTG_HS_GLOBAL::OTG_HS_TX0FSIZ_Peripheral, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_TX0FSIZ_PeripheralBase> ;
    using TX0FD = OTG_HS_GLOBAL_OTG_HS_TX0FSIZ_Peripheral_TX0FD_Values<OTG_HS_GLOBAL::OTG_HS_TX0FSIZ_Peripheral, 16, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_TX0FSIZ_PeripheralBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_TX0FSIZ_Peripheral_TX0FD_Values<OTG_HS_GLOBAL::OTG_HS_TX0FSIZ_Peripheral, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_TX0FSIZ_PeripheralPack  = Register<0x40040028, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_TX0FSIZ_PeripheralBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GNPTXSTSBase {} ;

  struct OTG_HS_GNPTXSTS : public RegisterBase<0x4004002C, 32, ReadMode>
  {
    using NPTXFSAV = OTG_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTXFSAV_Values<OTG_HS_GLOBAL::OTG_HS_GNPTXSTS, 0, 16, ReadMode, OTG_HS_GLOBALOTG_HS_GNPTXSTSBase> ;
    using NPTQXSAV = OTG_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTQXSAV_Values<OTG_HS_GLOBAL::OTG_HS_GNPTXSTS, 16, 8, ReadMode, OTG_HS_GLOBALOTG_HS_GNPTXSTSBase> ;
    using NPTXQTOP = OTG_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTXQTOP_Values<OTG_HS_GLOBAL::OTG_HS_GNPTXSTS, 24, 7, ReadMode, OTG_HS_GLOBALOTG_HS_GNPTXSTSBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTXQTOP_Values<OTG_HS_GLOBAL::OTG_HS_GNPTXSTS, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GNPTXSTSPack  = Register<0x4004002C, 32, ReadMode, OTG_HS_GLOBALOTG_HS_GNPTXSTSBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GCCFGBase {} ;

  struct OTG_HS_GCCFG : public RegisterBase<0x40040038, 32, ReadWriteMode>
  {
    using PWRDWN = OTG_HS_GLOBAL_OTG_HS_GCCFG_PWRDWN_Values<OTG_HS_GLOBAL::OTG_HS_GCCFG, 16, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GCCFGBase> ;
    using I2CPADEN = OTG_HS_GLOBAL_OTG_HS_GCCFG_I2CPADEN_Values<OTG_HS_GLOBAL::OTG_HS_GCCFG, 17, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GCCFGBase> ;
    using VBUSASEN = OTG_HS_GLOBAL_OTG_HS_GCCFG_VBUSASEN_Values<OTG_HS_GLOBAL::OTG_HS_GCCFG, 18, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GCCFGBase> ;
    using VBUSBSEN = OTG_HS_GLOBAL_OTG_HS_GCCFG_VBUSBSEN_Values<OTG_HS_GLOBAL::OTG_HS_GCCFG, 19, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GCCFGBase> ;
    using SOFOUTEN = OTG_HS_GLOBAL_OTG_HS_GCCFG_SOFOUTEN_Values<OTG_HS_GLOBAL::OTG_HS_GCCFG, 20, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GCCFGBase> ;
    using NOVBUSSENS = OTG_HS_GLOBAL_OTG_HS_GCCFG_NOVBUSSENS_Values<OTG_HS_GLOBAL::OTG_HS_GCCFG, 21, 1, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GCCFGBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GCCFG_NOVBUSSENS_Values<OTG_HS_GLOBAL::OTG_HS_GCCFG, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GCCFGPack  = Register<0x40040038, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_GCCFGBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_CIDBase {} ;

  struct OTG_HS_CID : public RegisterBase<0x4004003C, 32, ReadWriteMode>
  {
    using PRODUCT_ID = OTG_HS_GLOBAL_OTG_HS_CID_PRODUCT_ID_Values<OTG_HS_GLOBAL::OTG_HS_CID, 0, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_CIDBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_CID_PRODUCT_ID_Values<OTG_HS_GLOBAL::OTG_HS_CID, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_CIDPack  = Register<0x4004003C, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_CIDBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_HPTXFSIZBase {} ;

  struct OTG_HS_HPTXFSIZ : public RegisterBase<0x40040100, 32, ReadWriteMode>
  {
    using PTXSA = OTG_HS_GLOBAL_OTG_HS_HPTXFSIZ_PTXSA_Values<OTG_HS_GLOBAL::OTG_HS_HPTXFSIZ, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_HPTXFSIZBase> ;
    using PTXFD = OTG_HS_GLOBAL_OTG_HS_HPTXFSIZ_PTXFD_Values<OTG_HS_GLOBAL::OTG_HS_HPTXFSIZ, 16, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_HPTXFSIZBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_HPTXFSIZ_PTXFD_Values<OTG_HS_GLOBAL::OTG_HS_HPTXFSIZ, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_HPTXFSIZPack  = Register<0x40040100, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_HPTXFSIZBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_DIEPTXF1Base {} ;

  struct OTG_HS_DIEPTXF1 : public RegisterBase<0x40040104, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG_HS_GLOBAL_OTG_HS_DIEPTXF1_INEPTXSA_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF1, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF1Base> ;
    using INEPTXFD = OTG_HS_GLOBAL_OTG_HS_DIEPTXF1_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF1, 16, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF1Base> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_DIEPTXF1_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF1Pack  = Register<0x40040104, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF1Base, T...> ;

  struct OTG_HS_GLOBALOTG_HS_DIEPTXF2Base {} ;

  struct OTG_HS_DIEPTXF2 : public RegisterBase<0x40040108, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG_HS_GLOBAL_OTG_HS_DIEPTXF2_INEPTXSA_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF2, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF2Base> ;
    using INEPTXFD = OTG_HS_GLOBAL_OTG_HS_DIEPTXF2_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF2, 16, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF2Base> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_DIEPTXF2_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF2Pack  = Register<0x40040108, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF2Base, T...> ;

  struct OTG_HS_GLOBALOTG_HS_DIEPTXF3Base {} ;

  struct OTG_HS_DIEPTXF3 : public RegisterBase<0x4004011C, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG_HS_GLOBAL_OTG_HS_DIEPTXF3_INEPTXSA_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF3, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF3Base> ;
    using INEPTXFD = OTG_HS_GLOBAL_OTG_HS_DIEPTXF3_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF3, 16, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF3Base> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_DIEPTXF3_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF3Pack  = Register<0x4004011C, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF3Base, T...> ;

  struct OTG_HS_GLOBALOTG_HS_DIEPTXF4Base {} ;

  struct OTG_HS_DIEPTXF4 : public RegisterBase<0x40040120, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG_HS_GLOBAL_OTG_HS_DIEPTXF4_INEPTXSA_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF4, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF4Base> ;
    using INEPTXFD = OTG_HS_GLOBAL_OTG_HS_DIEPTXF4_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF4, 16, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF4Base> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_DIEPTXF4_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF4Pack  = Register<0x40040120, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF4Base, T...> ;

  struct OTG_HS_GLOBALOTG_HS_DIEPTXF5Base {} ;

  struct OTG_HS_DIEPTXF5 : public RegisterBase<0x40040124, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG_HS_GLOBAL_OTG_HS_DIEPTXF5_INEPTXSA_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF5, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF5Base> ;
    using INEPTXFD = OTG_HS_GLOBAL_OTG_HS_DIEPTXF5_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF5, 16, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF5Base> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_DIEPTXF5_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF5Pack  = Register<0x40040124, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF5Base, T...> ;

  struct OTG_HS_GLOBALOTG_HS_DIEPTXF6Base {} ;

  struct OTG_HS_DIEPTXF6 : public RegisterBase<0x40040128, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG_HS_GLOBAL_OTG_HS_DIEPTXF6_INEPTXSA_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF6, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF6Base> ;
    using INEPTXFD = OTG_HS_GLOBAL_OTG_HS_DIEPTXF6_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF6, 16, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF6Base> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_DIEPTXF6_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF6, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF6Pack  = Register<0x40040128, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF6Base, T...> ;

  struct OTG_HS_GLOBALOTG_HS_DIEPTXF7Base {} ;

  struct OTG_HS_DIEPTXF7 : public RegisterBase<0x4004012C, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG_HS_GLOBAL_OTG_HS_DIEPTXF7_INEPTXSA_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF7, 0, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF7Base> ;
    using INEPTXFD = OTG_HS_GLOBAL_OTG_HS_DIEPTXF7_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF7, 16, 16, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF7Base> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_DIEPTXF7_INEPTXFD_Values<OTG_HS_GLOBAL::OTG_HS_DIEPTXF7, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF7Pack  = Register<0x4004012C, 32, ReadWriteMode, OTG_HS_GLOBALOTG_HS_DIEPTXF7Base, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GRXSTSR_PeripheralBase {} ;

  struct OTG_HS_GRXSTSR_Peripheral : public RegisterBase<0x4004001C, 32, ReadMode>
  {
    using EPNUM = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Peripheral_EPNUM_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Peripheral, 0, 4, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_PeripheralBase> ;
    using BCNT = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Peripheral_BCNT_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Peripheral, 4, 11, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_PeripheralBase> ;
    using DPID = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Peripheral_DPID_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Peripheral, 15, 2, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_PeripheralBase> ;
    using PKTSTS = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Peripheral_PKTSTS_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Peripheral, 17, 4, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_PeripheralBase> ;
    using FRMNUM = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Peripheral_FRMNUM_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Peripheral, 21, 4, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_PeripheralBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GRXSTSR_Peripheral_FRMNUM_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSR_Peripheral, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRXSTSR_PeripheralPack  = Register<0x4004001C, 32, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSR_PeripheralBase, T...> ;

  struct OTG_HS_GLOBALOTG_HS_GRXSTSP_PeripheralBase {} ;

  struct OTG_HS_GRXSTSP_Peripheral : public RegisterBase<0x40040020, 32, ReadMode>
  {
    using EPNUM = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Peripheral_EPNUM_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Peripheral, 0, 4, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_PeripheralBase> ;
    using BCNT = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Peripheral_BCNT_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Peripheral, 4, 11, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_PeripheralBase> ;
    using DPID = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Peripheral_DPID_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Peripheral, 15, 2, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_PeripheralBase> ;
    using PKTSTS = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Peripheral_PKTSTS_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Peripheral, 17, 4, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_PeripheralBase> ;
    using FRMNUM = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Peripheral_FRMNUM_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Peripheral, 21, 4, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_PeripheralBase> ;
    using FieldValues = OTG_HS_GLOBAL_OTG_HS_GRXSTSP_Peripheral_FRMNUM_Values<OTG_HS_GLOBAL::OTG_HS_GRXSTSP_Peripheral, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRXSTSP_PeripheralPack  = Register<0x40040020, 32, ReadMode, OTG_HS_GLOBALOTG_HS_GRXSTSP_PeripheralBase, T...> ;

} ;

#endif //#if !defined(OTGHSGLOBALREGISTERS_HPP)
