/*******************************************************************************
* Filename      : otghsdeviceregisters.hpp
*
* Details       : USB on the go high speed. This header file is auto-generated
*                 for STM32F407 device.
*
*
*******************************************************************************/

#if !defined(OTGHSDEVICEREGISTERS_HPP)
#define OTGHSDEVICEREGISTERS_HPP

#include "otghsdevicefieldvalues.hpp"  //for Bits Fields defs 
#include "registerbase.hpp"   //for RegisterBase
#include "register.hpp"       //for Register
#include "accessmode.hpp"     //for ReadMode, WriteMode, ReadWriteMode  

struct OTG_HS_DEVICE
{
  struct OTG_HS_DEVICEOTG_HS_DCFGBase {} ;

  struct OTG_HS_DCFG : public RegisterBase<0x40040800, 32, ReadWriteMode>
  {
    using DSPD = OTG_HS_DEVICE_OTG_HS_DCFG_DSPD_Values<OTG_HS_DEVICE::OTG_HS_DCFG, 0, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCFGBase> ;
    using NZLSOHSK = OTG_HS_DEVICE_OTG_HS_DCFG_NZLSOHSK_Values<OTG_HS_DEVICE::OTG_HS_DCFG, 2, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCFGBase> ;
    using DAD = OTG_HS_DEVICE_OTG_HS_DCFG_DAD_Values<OTG_HS_DEVICE::OTG_HS_DCFG, 4, 7, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCFGBase> ;
    using PFIVL = OTG_HS_DEVICE_OTG_HS_DCFG_PFIVL_Values<OTG_HS_DEVICE::OTG_HS_DCFG, 11, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCFGBase> ;
    using PERSCHIVL = OTG_HS_DEVICE_OTG_HS_DCFG_PERSCHIVL_Values<OTG_HS_DEVICE::OTG_HS_DCFG, 24, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCFGBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DCFG_PERSCHIVL_Values<OTG_HS_DEVICE::OTG_HS_DCFG, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DCFGPack  = Register<0x40040800, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCFGBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DCTLBase {} ;

  struct OTG_HS_DCTL : public RegisterBase<0x40040804, 32, ReadWriteMode>
  {
    using RWUSIG = OTG_HS_DEVICE_OTG_HS_DCTL_RWUSIG_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCTLBase> ;
    using SDIS = OTG_HS_DEVICE_OTG_HS_DCTL_SDIS_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCTLBase> ;
    using GINSTS = OTG_HS_DEVICE_OTG_HS_DCTL_GINSTS_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 2, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DCTLBase> ;
    using GONSTS = OTG_HS_DEVICE_OTG_HS_DCTL_GONSTS_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 3, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DCTLBase> ;
    using TCTL = OTG_HS_DEVICE_OTG_HS_DCTL_TCTL_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 4, 3, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCTLBase> ;
    using SGINAK = OTG_HS_DEVICE_OTG_HS_DCTL_SGINAK_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 7, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DCTLBase> ;
    using CGINAK = OTG_HS_DEVICE_OTG_HS_DCTL_CGINAK_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 8, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DCTLBase> ;
    using SGONAK = OTG_HS_DEVICE_OTG_HS_DCTL_SGONAK_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 9, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DCTLBase> ;
    using CGONAK = OTG_HS_DEVICE_OTG_HS_DCTL_CGONAK_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 10, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DCTLBase> ;
    using POPRGDNE = OTG_HS_DEVICE_OTG_HS_DCTL_POPRGDNE_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 11, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCTLBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DCTL_POPRGDNE_Values<OTG_HS_DEVICE::OTG_HS_DCTL, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DCTLPack  = Register<0x40040804, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DCTLBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DSTSBase {} ;

  struct OTG_HS_DSTS : public RegisterBase<0x40040808, 32, ReadMode>
  {
    using SUSPSTS = OTG_HS_DEVICE_OTG_HS_DSTS_SUSPSTS_Values<OTG_HS_DEVICE::OTG_HS_DSTS, 0, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DSTSBase> ;
    using ENUMSPD = OTG_HS_DEVICE_OTG_HS_DSTS_ENUMSPD_Values<OTG_HS_DEVICE::OTG_HS_DSTS, 1, 2, ReadMode, OTG_HS_DEVICEOTG_HS_DSTSBase> ;
    using EERR = OTG_HS_DEVICE_OTG_HS_DSTS_EERR_Values<OTG_HS_DEVICE::OTG_HS_DSTS, 3, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DSTSBase> ;
    using FNSOF = OTG_HS_DEVICE_OTG_HS_DSTS_FNSOF_Values<OTG_HS_DEVICE::OTG_HS_DSTS, 8, 14, ReadMode, OTG_HS_DEVICEOTG_HS_DSTSBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DSTS_FNSOF_Values<OTG_HS_DEVICE::OTG_HS_DSTS, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DSTSPack  = Register<0x40040808, 32, ReadMode, OTG_HS_DEVICEOTG_HS_DSTSBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPMSKBase {} ;

  struct OTG_HS_DIEPMSK : public RegisterBase<0x40040810, 32, ReadWriteMode>
  {
    using XFRCM = OTG_HS_DEVICE_OTG_HS_DIEPMSK_XFRCM_Values<OTG_HS_DEVICE::OTG_HS_DIEPMSK, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPMSKBase> ;
    using EPDM = OTG_HS_DEVICE_OTG_HS_DIEPMSK_EPDM_Values<OTG_HS_DEVICE::OTG_HS_DIEPMSK, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPMSKBase> ;
    using TOM = OTG_HS_DEVICE_OTG_HS_DIEPMSK_TOM_Values<OTG_HS_DEVICE::OTG_HS_DIEPMSK, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPMSKBase> ;
    using ITTXFEMSK = OTG_HS_DEVICE_OTG_HS_DIEPMSK_ITTXFEMSK_Values<OTG_HS_DEVICE::OTG_HS_DIEPMSK, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPMSKBase> ;
    using INEPNMM = OTG_HS_DEVICE_OTG_HS_DIEPMSK_INEPNMM_Values<OTG_HS_DEVICE::OTG_HS_DIEPMSK, 5, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPMSKBase> ;
    using INEPNEM = OTG_HS_DEVICE_OTG_HS_DIEPMSK_INEPNEM_Values<OTG_HS_DEVICE::OTG_HS_DIEPMSK, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPMSKBase> ;
    using TXFURM = OTG_HS_DEVICE_OTG_HS_DIEPMSK_TXFURM_Values<OTG_HS_DEVICE::OTG_HS_DIEPMSK, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPMSKBase> ;
    using BIM = OTG_HS_DEVICE_OTG_HS_DIEPMSK_BIM_Values<OTG_HS_DEVICE::OTG_HS_DIEPMSK, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPMSKBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPMSK_BIM_Values<OTG_HS_DEVICE::OTG_HS_DIEPMSK, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPMSKPack  = Register<0x40040810, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPMSKBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPMSKBase {} ;

  struct OTG_HS_DOEPMSK : public RegisterBase<0x40040814, 32, ReadWriteMode>
  {
    using XFRCM = OTG_HS_DEVICE_OTG_HS_DOEPMSK_XFRCM_Values<OTG_HS_DEVICE::OTG_HS_DOEPMSK, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPMSKBase> ;
    using EPDM = OTG_HS_DEVICE_OTG_HS_DOEPMSK_EPDM_Values<OTG_HS_DEVICE::OTG_HS_DOEPMSK, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPMSKBase> ;
    using STUPM = OTG_HS_DEVICE_OTG_HS_DOEPMSK_STUPM_Values<OTG_HS_DEVICE::OTG_HS_DOEPMSK, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPMSKBase> ;
    using OTEPDM = OTG_HS_DEVICE_OTG_HS_DOEPMSK_OTEPDM_Values<OTG_HS_DEVICE::OTG_HS_DOEPMSK, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPMSKBase> ;
    using B2BSTUP = OTG_HS_DEVICE_OTG_HS_DOEPMSK_B2BSTUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPMSK, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPMSKBase> ;
    using OPEM = OTG_HS_DEVICE_OTG_HS_DOEPMSK_OPEM_Values<OTG_HS_DEVICE::OTG_HS_DOEPMSK, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPMSKBase> ;
    using BOIM = OTG_HS_DEVICE_OTG_HS_DOEPMSK_BOIM_Values<OTG_HS_DEVICE::OTG_HS_DOEPMSK, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPMSKBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPMSK_BOIM_Values<OTG_HS_DEVICE::OTG_HS_DOEPMSK, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPMSKPack  = Register<0x40040814, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPMSKBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DAINTBase {} ;

  struct OTG_HS_DAINT : public RegisterBase<0x40040818, 32, ReadMode>
  {
    using IEPINT = OTG_HS_DEVICE_OTG_HS_DAINT_IEPINT_Values<OTG_HS_DEVICE::OTG_HS_DAINT, 0, 16, ReadMode, OTG_HS_DEVICEOTG_HS_DAINTBase> ;
    using OEPINT = OTG_HS_DEVICE_OTG_HS_DAINT_OEPINT_Values<OTG_HS_DEVICE::OTG_HS_DAINT, 16, 16, ReadMode, OTG_HS_DEVICEOTG_HS_DAINTBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DAINT_OEPINT_Values<OTG_HS_DEVICE::OTG_HS_DAINT, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DAINTPack  = Register<0x40040818, 32, ReadMode, OTG_HS_DEVICEOTG_HS_DAINTBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DAINTMSKBase {} ;

  struct OTG_HS_DAINTMSK : public RegisterBase<0x4004081C, 32, ReadWriteMode>
  {
    using IEPM = OTG_HS_DEVICE_OTG_HS_DAINTMSK_IEPM_Values<OTG_HS_DEVICE::OTG_HS_DAINTMSK, 0, 16, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DAINTMSKBase> ;
    using OEPM = OTG_HS_DEVICE_OTG_HS_DAINTMSK_OEPM_Values<OTG_HS_DEVICE::OTG_HS_DAINTMSK, 16, 16, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DAINTMSKBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DAINTMSK_OEPM_Values<OTG_HS_DEVICE::OTG_HS_DAINTMSK, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DAINTMSKPack  = Register<0x4004081C, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DAINTMSKBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DVBUSDISBase {} ;

  struct OTG_HS_DVBUSDIS : public RegisterBase<0x40040828, 32, ReadWriteMode>
  {
    using VBUSDT = OTG_HS_DEVICE_OTG_HS_DVBUSDIS_VBUSDT_Values<OTG_HS_DEVICE::OTG_HS_DVBUSDIS, 0, 16, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DVBUSDISBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DVBUSDIS_VBUSDT_Values<OTG_HS_DEVICE::OTG_HS_DVBUSDIS, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DVBUSDISPack  = Register<0x40040828, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DVBUSDISBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DVBUSPULSEBase {} ;

  struct OTG_HS_DVBUSPULSE : public RegisterBase<0x4004082C, 32, ReadWriteMode>
  {
    using DVBUSP = OTG_HS_DEVICE_OTG_HS_DVBUSPULSE_DVBUSP_Values<OTG_HS_DEVICE::OTG_HS_DVBUSPULSE, 0, 12, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DVBUSPULSEBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DVBUSPULSE_DVBUSP_Values<OTG_HS_DEVICE::OTG_HS_DVBUSPULSE, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DVBUSPULSEPack  = Register<0x4004082C, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DVBUSPULSEBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DTHRCTLBase {} ;

  struct OTG_HS_DTHRCTL : public RegisterBase<0x40040830, 32, ReadWriteMode>
  {
    using NONISOTHREN = OTG_HS_DEVICE_OTG_HS_DTHRCTL_NONISOTHREN_Values<OTG_HS_DEVICE::OTG_HS_DTHRCTL, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DTHRCTLBase> ;
    using ISOTHREN = OTG_HS_DEVICE_OTG_HS_DTHRCTL_ISOTHREN_Values<OTG_HS_DEVICE::OTG_HS_DTHRCTL, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DTHRCTLBase> ;
    using TXTHRLEN = OTG_HS_DEVICE_OTG_HS_DTHRCTL_TXTHRLEN_Values<OTG_HS_DEVICE::OTG_HS_DTHRCTL, 2, 9, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DTHRCTLBase> ;
    using RXTHREN = OTG_HS_DEVICE_OTG_HS_DTHRCTL_RXTHREN_Values<OTG_HS_DEVICE::OTG_HS_DTHRCTL, 16, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DTHRCTLBase> ;
    using RXTHRLEN = OTG_HS_DEVICE_OTG_HS_DTHRCTL_RXTHRLEN_Values<OTG_HS_DEVICE::OTG_HS_DTHRCTL, 17, 9, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DTHRCTLBase> ;
    using ARPEN = OTG_HS_DEVICE_OTG_HS_DTHRCTL_ARPEN_Values<OTG_HS_DEVICE::OTG_HS_DTHRCTL, 27, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DTHRCTLBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DTHRCTL_ARPEN_Values<OTG_HS_DEVICE::OTG_HS_DTHRCTL, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DTHRCTLPack  = Register<0x40040830, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DTHRCTLBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPEMPMSKBase {} ;

  struct OTG_HS_DIEPEMPMSK : public RegisterBase<0x40040834, 32, ReadWriteMode>
  {
    using INEPTXFEM = OTG_HS_DEVICE_OTG_HS_DIEPEMPMSK_INEPTXFEM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEMPMSK, 0, 16, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEMPMSKBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPEMPMSK_INEPTXFEM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEMPMSK, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPEMPMSKPack  = Register<0x40040834, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEMPMSKBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DEACHINTBase {} ;

  struct OTG_HS_DEACHINT : public RegisterBase<0x40040838, 32, ReadWriteMode>
  {
    using IEP1INT = OTG_HS_DEVICE_OTG_HS_DEACHINT_IEP1INT_Values<OTG_HS_DEVICE::OTG_HS_DEACHINT, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DEACHINTBase> ;
    using OEP1INT = OTG_HS_DEVICE_OTG_HS_DEACHINT_OEP1INT_Values<OTG_HS_DEVICE::OTG_HS_DEACHINT, 17, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DEACHINTBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DEACHINT_OEP1INT_Values<OTG_HS_DEVICE::OTG_HS_DEACHINT, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DEACHINTPack  = Register<0x40040838, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DEACHINTBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DEACHINTMSKBase {} ;

  struct OTG_HS_DEACHINTMSK : public RegisterBase<0x4004083C, 32, ReadWriteMode>
  {
    using IEP1INTM = OTG_HS_DEVICE_OTG_HS_DEACHINTMSK_IEP1INTM_Values<OTG_HS_DEVICE::OTG_HS_DEACHINTMSK, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DEACHINTMSKBase> ;
    using OEP1INTM = OTG_HS_DEVICE_OTG_HS_DEACHINTMSK_OEP1INTM_Values<OTG_HS_DEVICE::OTG_HS_DEACHINTMSK, 17, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DEACHINTMSKBase> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DEACHINTMSK_OEP1INTM_Values<OTG_HS_DEVICE::OTG_HS_DEACHINTMSK, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DEACHINTMSKPack  = Register<0x4004083C, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DEACHINTMSKBase, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base {} ;

  struct OTG_HS_DIEPEACHMSK1 : public RegisterBase<0x40040840, 32, ReadWriteMode>
  {
    using XFRCM = OTG_HS_DEVICE_OTG_HS_DIEPEACHMSK1_XFRCM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEACHMSK1, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base> ;
    using EPDM = OTG_HS_DEVICE_OTG_HS_DIEPEACHMSK1_EPDM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEACHMSK1, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base> ;
    using TOM = OTG_HS_DEVICE_OTG_HS_DIEPEACHMSK1_TOM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEACHMSK1, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base> ;
    using ITTXFEMSK = OTG_HS_DEVICE_OTG_HS_DIEPEACHMSK1_ITTXFEMSK_Values<OTG_HS_DEVICE::OTG_HS_DIEPEACHMSK1, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base> ;
    using INEPNMM = OTG_HS_DEVICE_OTG_HS_DIEPEACHMSK1_INEPNMM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEACHMSK1, 5, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base> ;
    using INEPNEM = OTG_HS_DEVICE_OTG_HS_DIEPEACHMSK1_INEPNEM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEACHMSK1, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base> ;
    using TXFURM = OTG_HS_DEVICE_OTG_HS_DIEPEACHMSK1_TXFURM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEACHMSK1, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base> ;
    using BIM = OTG_HS_DEVICE_OTG_HS_DIEPEACHMSK1_BIM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEACHMSK1, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base> ;
    using NAKM = OTG_HS_DEVICE_OTG_HS_DIEPEACHMSK1_NAKM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEACHMSK1, 13, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPEACHMSK1_NAKM_Values<OTG_HS_DEVICE::OTG_HS_DIEPEACHMSK1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPEACHMSK1Pack  = Register<0x40040840, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPEACHMSK1Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base {} ;

  struct OTG_HS_DOEPEACHMSK1 : public RegisterBase<0x40040880, 32, ReadWriteMode>
  {
    using XFRCM = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_XFRCM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using EPDM = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_EPDM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using TOM = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_TOM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using ITTXFEMSK = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_ITTXFEMSK_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using INEPNMM = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_INEPNMM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 5, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using INEPNEM = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_INEPNEM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using TXFURM = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_TXFURM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using BIM = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_BIM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using BERRM = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_BERRM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 12, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using NAKM = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_NAKM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 13, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using NYETM = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_NYETM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 14, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPEACHMSK1_NYETM_Values<OTG_HS_DEVICE::OTG_HS_DOEPEACHMSK1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPEACHMSK1Pack  = Register<0x40040880, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPEACHMSK1Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPCTL0Base {} ;

  struct OTG_HS_DIEPCTL0 : public RegisterBase<0x40040900, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_Stall_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using TXFNUM = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_TXFNUM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 22, 4, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPCTL0_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL0, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPCTL0Pack  = Register<0x40040900, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL0Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPCTL1Base {} ;

  struct OTG_HS_DIEPCTL1 : public RegisterBase<0x40040920, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_Stall_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using TXFNUM = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_TXFNUM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 22, 4, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPCTL1_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPCTL1Pack  = Register<0x40040920, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL1Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPCTL2Base {} ;

  struct OTG_HS_DIEPCTL2 : public RegisterBase<0x40040940, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_Stall_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using TXFNUM = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_TXFNUM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 22, 4, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPCTL2_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPCTL2Pack  = Register<0x40040940, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL2Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPCTL3Base {} ;

  struct OTG_HS_DIEPCTL3 : public RegisterBase<0x40040960, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_Stall_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using TXFNUM = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_TXFNUM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 22, 4, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPCTL3_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPCTL3Pack  = Register<0x40040960, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL3Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPCTL4Base {} ;

  struct OTG_HS_DIEPCTL4 : public RegisterBase<0x40040980, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_Stall_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using TXFNUM = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_TXFNUM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 22, 4, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPCTL4_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPCTL4Pack  = Register<0x40040980, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL4Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPCTL5Base {} ;

  struct OTG_HS_DIEPCTL5 : public RegisterBase<0x400409A0, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_Stall_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using TXFNUM = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_TXFNUM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 22, 4, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPCTL5_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPCTL5Pack  = Register<0x400409A0, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL5Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPCTL6Base {} ;

  struct OTG_HS_DIEPCTL6 : public RegisterBase<0x400409C0, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_Stall_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using TXFNUM = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_TXFNUM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 22, 4, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPCTL6_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL6, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPCTL6Pack  = Register<0x400409C0, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL6Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPCTL7Base {} ;

  struct OTG_HS_DIEPCTL7 : public RegisterBase<0x400409E0, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_Stall_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using TXFNUM = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_TXFNUM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 22, 4, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPCTL7_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DIEPCTL7, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPCTL7Pack  = Register<0x400409E0, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPCTL7Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPINT0Base {} ;

  struct OTG_HS_DIEPINT0 : public RegisterBase<0x40040908, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DIEPINT0_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DIEPINT0_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using TOC = OTG_HS_DEVICE_OTG_HS_DIEPINT0_TOC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using ITTXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT0_ITTXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using INEPNE = OTG_HS_DEVICE_OTG_HS_DIEPINT0_INEPNE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using TXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT0_TXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 7, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using TXFIFOUDRN = OTG_HS_DEVICE_OTG_HS_DIEPINT0_TXFIFOUDRN_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using BNA = OTG_HS_DEVICE_OTG_HS_DIEPINT0_BNA_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using PKTDRPSTS = OTG_HS_DEVICE_OTG_HS_DIEPINT0_PKTDRPSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 11, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using BERR = OTG_HS_DEVICE_OTG_HS_DIEPINT0_BERR_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 12, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using NAK = OTG_HS_DEVICE_OTG_HS_DIEPINT0_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 13, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPINT0_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT0, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPINT0Pack  = Register<0x40040908, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT0Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPINT1Base {} ;

  struct OTG_HS_DIEPINT1 : public RegisterBase<0x40040928, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DIEPINT1_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DIEPINT1_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using TOC = OTG_HS_DEVICE_OTG_HS_DIEPINT1_TOC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using ITTXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT1_ITTXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using INEPNE = OTG_HS_DEVICE_OTG_HS_DIEPINT1_INEPNE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using TXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT1_TXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 7, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using TXFIFOUDRN = OTG_HS_DEVICE_OTG_HS_DIEPINT1_TXFIFOUDRN_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using BNA = OTG_HS_DEVICE_OTG_HS_DIEPINT1_BNA_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using PKTDRPSTS = OTG_HS_DEVICE_OTG_HS_DIEPINT1_PKTDRPSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 11, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using BERR = OTG_HS_DEVICE_OTG_HS_DIEPINT1_BERR_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 12, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using NAK = OTG_HS_DEVICE_OTG_HS_DIEPINT1_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 13, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPINT1_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPINT1Pack  = Register<0x40040928, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT1Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPINT2Base {} ;

  struct OTG_HS_DIEPINT2 : public RegisterBase<0x40040948, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DIEPINT2_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DIEPINT2_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using TOC = OTG_HS_DEVICE_OTG_HS_DIEPINT2_TOC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using ITTXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT2_ITTXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using INEPNE = OTG_HS_DEVICE_OTG_HS_DIEPINT2_INEPNE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using TXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT2_TXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 7, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using TXFIFOUDRN = OTG_HS_DEVICE_OTG_HS_DIEPINT2_TXFIFOUDRN_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using BNA = OTG_HS_DEVICE_OTG_HS_DIEPINT2_BNA_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using PKTDRPSTS = OTG_HS_DEVICE_OTG_HS_DIEPINT2_PKTDRPSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 11, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using BERR = OTG_HS_DEVICE_OTG_HS_DIEPINT2_BERR_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 12, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using NAK = OTG_HS_DEVICE_OTG_HS_DIEPINT2_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 13, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPINT2_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPINT2Pack  = Register<0x40040948, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT2Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPINT3Base {} ;

  struct OTG_HS_DIEPINT3 : public RegisterBase<0x40040968, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DIEPINT3_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DIEPINT3_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using TOC = OTG_HS_DEVICE_OTG_HS_DIEPINT3_TOC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using ITTXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT3_ITTXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using INEPNE = OTG_HS_DEVICE_OTG_HS_DIEPINT3_INEPNE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using TXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT3_TXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 7, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using TXFIFOUDRN = OTG_HS_DEVICE_OTG_HS_DIEPINT3_TXFIFOUDRN_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using BNA = OTG_HS_DEVICE_OTG_HS_DIEPINT3_BNA_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using PKTDRPSTS = OTG_HS_DEVICE_OTG_HS_DIEPINT3_PKTDRPSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 11, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using BERR = OTG_HS_DEVICE_OTG_HS_DIEPINT3_BERR_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 12, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using NAK = OTG_HS_DEVICE_OTG_HS_DIEPINT3_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 13, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPINT3_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPINT3Pack  = Register<0x40040968, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT3Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPINT4Base {} ;

  struct OTG_HS_DIEPINT4 : public RegisterBase<0x40040988, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DIEPINT4_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DIEPINT4_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using TOC = OTG_HS_DEVICE_OTG_HS_DIEPINT4_TOC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using ITTXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT4_ITTXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using INEPNE = OTG_HS_DEVICE_OTG_HS_DIEPINT4_INEPNE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using TXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT4_TXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 7, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using TXFIFOUDRN = OTG_HS_DEVICE_OTG_HS_DIEPINT4_TXFIFOUDRN_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using BNA = OTG_HS_DEVICE_OTG_HS_DIEPINT4_BNA_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using PKTDRPSTS = OTG_HS_DEVICE_OTG_HS_DIEPINT4_PKTDRPSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 11, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using BERR = OTG_HS_DEVICE_OTG_HS_DIEPINT4_BERR_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 12, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using NAK = OTG_HS_DEVICE_OTG_HS_DIEPINT4_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 13, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPINT4_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPINT4Pack  = Register<0x40040988, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT4Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPINT5Base {} ;

  struct OTG_HS_DIEPINT5 : public RegisterBase<0x400409A8, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DIEPINT5_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DIEPINT5_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using TOC = OTG_HS_DEVICE_OTG_HS_DIEPINT5_TOC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using ITTXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT5_ITTXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using INEPNE = OTG_HS_DEVICE_OTG_HS_DIEPINT5_INEPNE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using TXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT5_TXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 7, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using TXFIFOUDRN = OTG_HS_DEVICE_OTG_HS_DIEPINT5_TXFIFOUDRN_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using BNA = OTG_HS_DEVICE_OTG_HS_DIEPINT5_BNA_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using PKTDRPSTS = OTG_HS_DEVICE_OTG_HS_DIEPINT5_PKTDRPSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 11, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using BERR = OTG_HS_DEVICE_OTG_HS_DIEPINT5_BERR_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 12, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using NAK = OTG_HS_DEVICE_OTG_HS_DIEPINT5_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 13, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPINT5_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPINT5Pack  = Register<0x400409A8, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT5Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPINT6Base {} ;

  struct OTG_HS_DIEPINT6 : public RegisterBase<0x400409C8, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DIEPINT6_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DIEPINT6_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using TOC = OTG_HS_DEVICE_OTG_HS_DIEPINT6_TOC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using ITTXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT6_ITTXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using INEPNE = OTG_HS_DEVICE_OTG_HS_DIEPINT6_INEPNE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using TXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT6_TXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 7, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using TXFIFOUDRN = OTG_HS_DEVICE_OTG_HS_DIEPINT6_TXFIFOUDRN_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using BNA = OTG_HS_DEVICE_OTG_HS_DIEPINT6_BNA_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using PKTDRPSTS = OTG_HS_DEVICE_OTG_HS_DIEPINT6_PKTDRPSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 11, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using BERR = OTG_HS_DEVICE_OTG_HS_DIEPINT6_BERR_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 12, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using NAK = OTG_HS_DEVICE_OTG_HS_DIEPINT6_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 13, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPINT6_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT6, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPINT6Pack  = Register<0x400409C8, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT6Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPINT7Base {} ;

  struct OTG_HS_DIEPINT7 : public RegisterBase<0x400409E8, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DIEPINT7_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DIEPINT7_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using TOC = OTG_HS_DEVICE_OTG_HS_DIEPINT7_TOC_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using ITTXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT7_ITTXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using INEPNE = OTG_HS_DEVICE_OTG_HS_DIEPINT7_INEPNE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using TXFE = OTG_HS_DEVICE_OTG_HS_DIEPINT7_TXFE_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 7, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using TXFIFOUDRN = OTG_HS_DEVICE_OTG_HS_DIEPINT7_TXFIFOUDRN_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 8, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using BNA = OTG_HS_DEVICE_OTG_HS_DIEPINT7_BNA_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 9, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using PKTDRPSTS = OTG_HS_DEVICE_OTG_HS_DIEPINT7_PKTDRPSTS_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 11, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using BERR = OTG_HS_DEVICE_OTG_HS_DIEPINT7_BERR_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 12, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using NAK = OTG_HS_DEVICE_OTG_HS_DIEPINT7_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 13, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPINT7_NAK_Values<OTG_HS_DEVICE::OTG_HS_DIEPINT7, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPINT7Pack  = Register<0x400409E8, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPINT7Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPTSIZ0Base {} ;

  struct OTG_HS_DIEPTSIZ0 : public RegisterBase<0x40040910, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ0_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ0, 0, 7, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ0Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ0_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ0, 19, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ0Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ0_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ0, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTSIZ0Pack  = Register<0x40040910, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ0Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPDMA1Base {} ;

  struct OTG_HS_DIEPDMA1 : public RegisterBase<0x40040914, 32, ReadWriteMode>
  {
    using DMAADDR = OTG_HS_DEVICE_OTG_HS_DIEPDMA1_DMAADDR_Values<OTG_HS_DEVICE::OTG_HS_DIEPDMA1, 0, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPDMA1Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPDMA1_DMAADDR_Values<OTG_HS_DEVICE::OTG_HS_DIEPDMA1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPDMA1Pack  = Register<0x40040914, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPDMA1Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPDMA2Base {} ;

  struct OTG_HS_DIEPDMA2 : public RegisterBase<0x40040934, 32, ReadWriteMode>
  {
    using DMAADDR = OTG_HS_DEVICE_OTG_HS_DIEPDMA2_DMAADDR_Values<OTG_HS_DEVICE::OTG_HS_DIEPDMA2, 0, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPDMA2Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPDMA2_DMAADDR_Values<OTG_HS_DEVICE::OTG_HS_DIEPDMA2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPDMA2Pack  = Register<0x40040934, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPDMA2Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPDMA3Base {} ;

  struct OTG_HS_DIEPDMA3 : public RegisterBase<0x40040954, 32, ReadWriteMode>
  {
    using DMAADDR = OTG_HS_DEVICE_OTG_HS_DIEPDMA3_DMAADDR_Values<OTG_HS_DEVICE::OTG_HS_DIEPDMA3, 0, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPDMA3Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPDMA3_DMAADDR_Values<OTG_HS_DEVICE::OTG_HS_DIEPDMA3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPDMA3Pack  = Register<0x40040954, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPDMA3Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPDMA4Base {} ;

  struct OTG_HS_DIEPDMA4 : public RegisterBase<0x40040974, 32, ReadWriteMode>
  {
    using DMAADDR = OTG_HS_DEVICE_OTG_HS_DIEPDMA4_DMAADDR_Values<OTG_HS_DEVICE::OTG_HS_DIEPDMA4, 0, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPDMA4Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPDMA4_DMAADDR_Values<OTG_HS_DEVICE::OTG_HS_DIEPDMA4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPDMA4Pack  = Register<0x40040974, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPDMA4Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPDMA5Base {} ;

  struct OTG_HS_DIEPDMA5 : public RegisterBase<0x40040994, 32, ReadWriteMode>
  {
    using DMAADDR = OTG_HS_DEVICE_OTG_HS_DIEPDMA5_DMAADDR_Values<OTG_HS_DEVICE::OTG_HS_DIEPDMA5, 0, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPDMA5Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPDMA5_DMAADDR_Values<OTG_HS_DEVICE::OTG_HS_DIEPDMA5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPDMA5Pack  = Register<0x40040994, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPDMA5Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DTXFSTS0Base {} ;

  struct OTG_HS_DTXFSTS0 : public RegisterBase<0x40040918, 32, ReadMode>
  {
    using INEPTFSAV = OTG_HS_DEVICE_OTG_HS_DTXFSTS0_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS0, 0, 16, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS0Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DTXFSTS0_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS0, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DTXFSTS0Pack  = Register<0x40040918, 32, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS0Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DTXFSTS1Base {} ;

  struct OTG_HS_DTXFSTS1 : public RegisterBase<0x40040938, 32, ReadMode>
  {
    using INEPTFSAV = OTG_HS_DEVICE_OTG_HS_DTXFSTS1_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS1, 0, 16, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS1Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DTXFSTS1_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DTXFSTS1Pack  = Register<0x40040938, 32, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS1Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DTXFSTS2Base {} ;

  struct OTG_HS_DTXFSTS2 : public RegisterBase<0x40040958, 32, ReadMode>
  {
    using INEPTFSAV = OTG_HS_DEVICE_OTG_HS_DTXFSTS2_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS2, 0, 16, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS2Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DTXFSTS2_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DTXFSTS2Pack  = Register<0x40040958, 32, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS2Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DTXFSTS3Base {} ;

  struct OTG_HS_DTXFSTS3 : public RegisterBase<0x40040978, 32, ReadMode>
  {
    using INEPTFSAV = OTG_HS_DEVICE_OTG_HS_DTXFSTS3_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS3, 0, 16, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS3Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DTXFSTS3_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DTXFSTS3Pack  = Register<0x40040978, 32, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS3Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DTXFSTS4Base {} ;

  struct OTG_HS_DTXFSTS4 : public RegisterBase<0x40040998, 32, ReadMode>
  {
    using INEPTFSAV = OTG_HS_DEVICE_OTG_HS_DTXFSTS4_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS4, 0, 16, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS4Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DTXFSTS4_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DTXFSTS4Pack  = Register<0x40040998, 32, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS4Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DTXFSTS5Base {} ;

  struct OTG_HS_DTXFSTS5 : public RegisterBase<0x400409B8, 32, ReadMode>
  {
    using INEPTFSAV = OTG_HS_DEVICE_OTG_HS_DTXFSTS5_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS5, 0, 16, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS5Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DTXFSTS5_INEPTFSAV_Values<OTG_HS_DEVICE::OTG_HS_DTXFSTS5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DTXFSTS5Pack  = Register<0x400409B8, 32, ReadMode, OTG_HS_DEVICEOTG_HS_DTXFSTS5Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPTSIZ1Base {} ;

  struct OTG_HS_DIEPTSIZ1 : public RegisterBase<0x40040930, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ1_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ1, 0, 19, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ1Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ1_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ1, 19, 10, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ1Base> ;
    using MCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ1_MCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ1, 29, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ1Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ1_MCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTSIZ1Pack  = Register<0x40040930, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ1Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPTSIZ2Base {} ;

  struct OTG_HS_DIEPTSIZ2 : public RegisterBase<0x40040950, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ2_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ2, 0, 19, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ2Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ2_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ2, 19, 10, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ2Base> ;
    using MCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ2_MCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ2, 29, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ2Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ2_MCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTSIZ2Pack  = Register<0x40040950, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ2Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPTSIZ3Base {} ;

  struct OTG_HS_DIEPTSIZ3 : public RegisterBase<0x40040970, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ3_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ3, 0, 19, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ3Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ3_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ3, 19, 10, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ3Base> ;
    using MCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ3_MCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ3, 29, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ3Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ3_MCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTSIZ3Pack  = Register<0x40040970, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ3Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPTSIZ4Base {} ;

  struct OTG_HS_DIEPTSIZ4 : public RegisterBase<0x40040990, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ4_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ4, 0, 19, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ4Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ4_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ4, 19, 10, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ4Base> ;
    using MCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ4_MCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ4, 29, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ4Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ4_MCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTSIZ4Pack  = Register<0x40040990, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ4Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DIEPTSIZ5Base {} ;

  struct OTG_HS_DIEPTSIZ5 : public RegisterBase<0x400409B0, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ5_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ5, 0, 19, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ5Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ5_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ5, 19, 10, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ5Base> ;
    using MCNT = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ5_MCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ5, 29, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ5Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DIEPTSIZ5_MCNT_Values<OTG_HS_DEVICE::OTG_HS_DIEPTSIZ5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTSIZ5Pack  = Register<0x400409B0, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DIEPTSIZ5Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPCTL0Base {} ;

  struct OTG_HS_DOEPCTL0 : public RegisterBase<0x40040B00, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 0, 2, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 15, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 18, 2, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base> ;
    using SNPM = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_SNPM_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 20, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_Stall_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 30, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 31, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPCTL0_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL0, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPCTL0Pack  = Register<0x40040B00, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL0Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPCTL1Base {} ;

  struct OTG_HS_DOEPCTL1 : public RegisterBase<0x40040B20, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using SNPM = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_SNPM_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 20, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_Stall_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPCTL1_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPCTL1Pack  = Register<0x40040B20, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL1Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPCTL2Base {} ;

  struct OTG_HS_DOEPCTL2 : public RegisterBase<0x40040B40, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using SNPM = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_SNPM_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 20, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_Stall_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPCTL2_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPCTL2Pack  = Register<0x40040B40, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL2Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPCTL3Base {} ;

  struct OTG_HS_DOEPCTL3 : public RegisterBase<0x40040B60, 32, ReadWriteMode>
  {
    using MPSIZ = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_MPSIZ_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 0, 11, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using USBAEP = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_USBAEP_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 15, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using EONUM_DPID = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_EONUM_DPID_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 16, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using NAKSTS = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_NAKSTS_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 17, 1, ReadMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using EPTYP = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_EPTYP_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 18, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using SNPM = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_SNPM_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 20, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using Stall = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_Stall_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 21, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using CNAK = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_CNAK_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 26, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using SNAK = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_SNAK_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 27, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using SD0PID_SEVNFRM = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_SD0PID_SEVNFRM_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 28, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using SODDFRM = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_SODDFRM_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 29, 1, WriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using EPDIS = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_EPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 30, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using EPENA = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 31, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPCTL3_EPENA_Values<OTG_HS_DEVICE::OTG_HS_DOEPCTL3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPCTL3Pack  = Register<0x40040B60, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPCTL3Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPINT0Base {} ;

  struct OTG_HS_DOEPINT0 : public RegisterBase<0x40040B08, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DOEPINT0_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT0, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT0Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DOEPINT0_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT0, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT0Base> ;
    using STUP = OTG_HS_DEVICE_OTG_HS_DOEPINT0_STUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT0, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT0Base> ;
    using OTEPDIS = OTG_HS_DEVICE_OTG_HS_DOEPINT0_OTEPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT0, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT0Base> ;
    using B2BSTUP = OTG_HS_DEVICE_OTG_HS_DOEPINT0_B2BSTUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT0, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT0Base> ;
    using NYET = OTG_HS_DEVICE_OTG_HS_DOEPINT0_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT0, 14, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT0Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPINT0_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT0, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPINT0Pack  = Register<0x40040B08, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT0Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPINT1Base {} ;

  struct OTG_HS_DOEPINT1 : public RegisterBase<0x40040B28, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DOEPINT1_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT1, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT1Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DOEPINT1_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT1, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT1Base> ;
    using STUP = OTG_HS_DEVICE_OTG_HS_DOEPINT1_STUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT1, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT1Base> ;
    using OTEPDIS = OTG_HS_DEVICE_OTG_HS_DOEPINT1_OTEPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT1, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT1Base> ;
    using B2BSTUP = OTG_HS_DEVICE_OTG_HS_DOEPINT1_B2BSTUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT1, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT1Base> ;
    using NYET = OTG_HS_DEVICE_OTG_HS_DOEPINT1_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT1, 14, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT1Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPINT1_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPINT1Pack  = Register<0x40040B28, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT1Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPINT2Base {} ;

  struct OTG_HS_DOEPINT2 : public RegisterBase<0x40040B48, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DOEPINT2_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT2, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT2Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DOEPINT2_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT2, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT2Base> ;
    using STUP = OTG_HS_DEVICE_OTG_HS_DOEPINT2_STUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT2, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT2Base> ;
    using OTEPDIS = OTG_HS_DEVICE_OTG_HS_DOEPINT2_OTEPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT2, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT2Base> ;
    using B2BSTUP = OTG_HS_DEVICE_OTG_HS_DOEPINT2_B2BSTUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT2, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT2Base> ;
    using NYET = OTG_HS_DEVICE_OTG_HS_DOEPINT2_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT2, 14, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT2Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPINT2_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPINT2Pack  = Register<0x40040B48, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT2Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPINT3Base {} ;

  struct OTG_HS_DOEPINT3 : public RegisterBase<0x40040B68, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DOEPINT3_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT3, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT3Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DOEPINT3_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT3, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT3Base> ;
    using STUP = OTG_HS_DEVICE_OTG_HS_DOEPINT3_STUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT3, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT3Base> ;
    using OTEPDIS = OTG_HS_DEVICE_OTG_HS_DOEPINT3_OTEPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT3, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT3Base> ;
    using B2BSTUP = OTG_HS_DEVICE_OTG_HS_DOEPINT3_B2BSTUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT3, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT3Base> ;
    using NYET = OTG_HS_DEVICE_OTG_HS_DOEPINT3_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT3, 14, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT3Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPINT3_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPINT3Pack  = Register<0x40040B68, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT3Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPINT4Base {} ;

  struct OTG_HS_DOEPINT4 : public RegisterBase<0x40040B88, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DOEPINT4_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT4, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT4Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DOEPINT4_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT4, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT4Base> ;
    using STUP = OTG_HS_DEVICE_OTG_HS_DOEPINT4_STUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT4, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT4Base> ;
    using OTEPDIS = OTG_HS_DEVICE_OTG_HS_DOEPINT4_OTEPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT4, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT4Base> ;
    using B2BSTUP = OTG_HS_DEVICE_OTG_HS_DOEPINT4_B2BSTUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT4, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT4Base> ;
    using NYET = OTG_HS_DEVICE_OTG_HS_DOEPINT4_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT4, 14, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT4Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPINT4_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPINT4Pack  = Register<0x40040B88, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT4Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPINT5Base {} ;

  struct OTG_HS_DOEPINT5 : public RegisterBase<0x40040BA8, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DOEPINT5_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT5, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT5Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DOEPINT5_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT5, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT5Base> ;
    using STUP = OTG_HS_DEVICE_OTG_HS_DOEPINT5_STUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT5, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT5Base> ;
    using OTEPDIS = OTG_HS_DEVICE_OTG_HS_DOEPINT5_OTEPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT5, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT5Base> ;
    using B2BSTUP = OTG_HS_DEVICE_OTG_HS_DOEPINT5_B2BSTUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT5, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT5Base> ;
    using NYET = OTG_HS_DEVICE_OTG_HS_DOEPINT5_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT5, 14, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT5Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPINT5_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPINT5Pack  = Register<0x40040BA8, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT5Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPINT6Base {} ;

  struct OTG_HS_DOEPINT6 : public RegisterBase<0x40040BC8, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DOEPINT6_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT6, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT6Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DOEPINT6_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT6, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT6Base> ;
    using STUP = OTG_HS_DEVICE_OTG_HS_DOEPINT6_STUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT6, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT6Base> ;
    using OTEPDIS = OTG_HS_DEVICE_OTG_HS_DOEPINT6_OTEPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT6, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT6Base> ;
    using B2BSTUP = OTG_HS_DEVICE_OTG_HS_DOEPINT6_B2BSTUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT6, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT6Base> ;
    using NYET = OTG_HS_DEVICE_OTG_HS_DOEPINT6_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT6, 14, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT6Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPINT6_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT6, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPINT6Pack  = Register<0x40040BC8, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT6Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPINT7Base {} ;

  struct OTG_HS_DOEPINT7 : public RegisterBase<0x40040BE8, 32, ReadWriteMode>
  {
    using XFRC = OTG_HS_DEVICE_OTG_HS_DOEPINT7_XFRC_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT7, 0, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT7Base> ;
    using EPDISD = OTG_HS_DEVICE_OTG_HS_DOEPINT7_EPDISD_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT7, 1, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT7Base> ;
    using STUP = OTG_HS_DEVICE_OTG_HS_DOEPINT7_STUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT7, 3, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT7Base> ;
    using OTEPDIS = OTG_HS_DEVICE_OTG_HS_DOEPINT7_OTEPDIS_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT7, 4, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT7Base> ;
    using B2BSTUP = OTG_HS_DEVICE_OTG_HS_DOEPINT7_B2BSTUP_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT7, 6, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT7Base> ;
    using NYET = OTG_HS_DEVICE_OTG_HS_DOEPINT7_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT7, 14, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT7Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPINT7_NYET_Values<OTG_HS_DEVICE::OTG_HS_DOEPINT7, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPINT7Pack  = Register<0x40040BE8, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPINT7Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPTSIZ0Base {} ;

  struct OTG_HS_DOEPTSIZ0 : public RegisterBase<0x40040B10, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ0_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ0, 0, 7, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ0Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ0_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ0, 19, 1, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ0Base> ;
    using STUPCNT = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ0_STUPCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ0, 29, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ0Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ0_STUPCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ0, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPTSIZ0Pack  = Register<0x40040B10, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ0Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPTSIZ1Base {} ;

  struct OTG_HS_DOEPTSIZ1 : public RegisterBase<0x40040B30, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ1_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ1, 0, 19, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ1Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ1_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ1, 19, 10, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ1Base> ;
    using RXDPID_STUPCNT = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ1_RXDPID_STUPCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ1, 29, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ1Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ1_RXDPID_STUPCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPTSIZ1Pack  = Register<0x40040B30, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ1Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPTSIZ2Base {} ;

  struct OTG_HS_DOEPTSIZ2 : public RegisterBase<0x40040B50, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ2_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ2, 0, 19, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ2Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ2_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ2, 19, 10, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ2Base> ;
    using RXDPID_STUPCNT = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ2_RXDPID_STUPCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ2, 29, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ2Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ2_RXDPID_STUPCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPTSIZ2Pack  = Register<0x40040B50, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ2Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPTSIZ3Base {} ;

  struct OTG_HS_DOEPTSIZ3 : public RegisterBase<0x40040B70, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ3_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ3, 0, 19, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ3Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ3_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ3, 19, 10, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ3Base> ;
    using RXDPID_STUPCNT = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ3_RXDPID_STUPCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ3, 29, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ3Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ3_RXDPID_STUPCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPTSIZ3Pack  = Register<0x40040B70, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ3Base, T...> ;

  struct OTG_HS_DEVICEOTG_HS_DOEPTSIZ4Base {} ;

  struct OTG_HS_DOEPTSIZ4 : public RegisterBase<0x40040B90, 32, ReadWriteMode>
  {
    using XFRSIZ = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ4_XFRSIZ_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ4, 0, 19, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ4Base> ;
    using PKTCNT = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ4_PKTCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ4, 19, 10, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ4Base> ;
    using RXDPID_STUPCNT = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ4_RXDPID_STUPCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ4, 29, 2, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ4Base> ;
    using FieldValues = OTG_HS_DEVICE_OTG_HS_DOEPTSIZ4_RXDPID_STUPCNT_Values<OTG_HS_DEVICE::OTG_HS_DOEPTSIZ4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DOEPTSIZ4Pack  = Register<0x40040B90, 32, ReadWriteMode, OTG_HS_DEVICEOTG_HS_DOEPTSIZ4Base, T...> ;

} ;

#endif //#if !defined(OTGHSDEVICEREGISTERS_HPP)
